const en = {
  appName: 'Antigravity Manager',
  common: {
    loading: 'Loading...',
    error: 'Error',
    unknown: 'Unknown',
    notAvailable: 'N/A',
    openMenu: 'Open menu',
  },
  status: {
    checking: 'Checking status...',
    running: 'Antigravity is running in background',
    stopped: 'Antigravity service stopped',
    services: 'Services',
    dashboard_title: 'Service status',
    open_dashboard: 'Open service status',
    checking_short: 'Checking...',
    running_short: 'Running',
    stopped_short: 'Stopped',
    all_running: 'All services running',
    all_stopped: 'All services stopped',
    partial_running: '{{running}}/{{total}} services running',
  },
  action: {
    stop: 'Stop',
    start: 'Start',
    switch: 'Switch',
    deleteBackup: 'Delete Backup',
    backupCurrent: 'Backup Current',
    retry: 'Retry',
    details: 'Details',
    openLogs: 'Open Log Directory',
  },
  update: {
    title: 'Updates',
    checking: 'Checking...',
    checkNow: 'Check for Updates',
    checkFailed: 'Unable to check for updates',
    upToDate: "You're up to date.",
    unsupported: 'Automatic update checks are not available on this platform.',
    available: {
      title: 'Update available',
      description: 'Version {{version}} is available on GitHub.',
      download: 'Download',
      dismiss: 'Dismiss',
      macosUnsignedNote:
        'This macOS build is not officially signed. If macOS blocks the app, follow the manual signing steps in the GitHub README or related issues.',
    },
  },
  error: {
    generic: 'An unexpected error occurred.',
    detailsTitle: 'Error details',
    detailsDescription:
      'Backend error details are shown below. They may include local file paths and stack frames.',
    keychainUnavailable: 'Keychain is unavailable.',
    keychainHint: {
      translocation: 'Detected macOS App Translocation. Move the app to /Applications and reopen.',
      keychainDenied:
        'Keychain access denied. The app may be unsigned; see README for the self-signing workaround.',
      signNotarize: 'Please use a signed and notarized build when available.',
    },
    dataMigrationFailed: 'Unable to decrypt legacy account data.',
    dataMigrationHint: {
      relogin: 'Please re-login or re-add your accounts.',
      clearData: 'If the issue persists, clear local account data and sign in again.',
    },
    antigravityStorageJsonNotFound:
      'Antigravity storage.json was not found. Open the target Antigravity app and sign in once, then try switching again.',
    antigravityProjectIdMissing:
      'This account is missing an Antigravity project ID. This may happen if the account has not signed in to the Antigravity app before. Please sign in once in the Antigravity app, then return to this tool and try switching again.',
    antigravityDatabasePermissionDenied:
      'Antigravity database storage is not writable. Check the configured Antigravity user-data directory or restart Antigravity Manager after opening Antigravity once.',
  },
  nav: {
    accounts: 'Accounts',
    proxy: 'API Proxy',
    settings: 'Settings',
  },
  editionSelection: {
    title: 'Choose Your Antigravity Edition',
    description:
      'Select which version of Antigravity you are using. This helps the Manager connect to the correct application.',
    edition1x: {
      name: 'Antigravity 1.x',
      description:
        'The original Antigravity application. Choose this if you are using the legacy version.',
    },
    edition20: {
      name: 'Antigravity IDE',
      description:
        'The new Antigravity IDE (2.0). Choose this if you are using the latest IDE version.',
    },
    confirm: 'Continue',
  },
  account: {
    current: 'Current',
    lastUsed: 'Last used {{time}}',
    switchToAntigravity: 'Switch to Antigravity',
    switchToIde: 'Switch to Antigravity IDE',
  },
  home: {
    title: 'Accounts',
    description: 'Manage your Antigravity Google Gemini accounts.',
    noBackups: {
      title: 'No backups found',
      description: 'Create a backup of your current Antigravity account to get started.',
      action: 'Backup Current Account',
    },
  },
  settings: {
    title: 'Settings',
    description: 'Manage application preferences.',
    general: 'General',
    connection: 'Connection',
    models: 'Models',
    appearance: {
      title: 'Appearance',
      description: 'Customize how Antigravity Manager looks on your device.',
    },
    darkMode: 'Dark Mode',
    darkModeDescription: 'Enable dark mode for better viewing at night.',
    language: {
      title: 'Language',
      description: 'Select your preferred language.',
      english: 'English',
      chinese: 'Chinese (Simplified)',
      russian: 'Russian',
      vietnamese: 'Vietnamese',
      turkish: 'Turkish',
      french: 'French',
    },
    about: {
      title: 'About',
      description: 'Application information.',
    },
    version: 'Version',
    platform: 'Platform',
    license: 'License',
    openLogDir: 'Open',
    toast: {
      saved: {
        title: 'Settings saved',
        description: 'Your configuration has been updated.',
      },
      saveFailed: {
        title: 'Error saving settings',
      },
    },
    account: {
      title: 'Account Settings',
      description: 'Configure automatic account refresh and sync.',
      auto_refresh: 'Auto Refresh Quota',
      auto_refresh_desc: 'Periodically refresh quota info for all accounts',
      auto_sync: 'Auto Sync Current Account',
      auto_sync_desc: 'Periodically sync active account information',
      antigravity_executable: 'Antigravity executable',
      antigravity_executable_desc:
        'Optional path used to find portable mode data and launch Antigravity.',
      antigravity_executable_placeholder:
        'Example: C:\\Program Files\\Antigravity\\Antigravity.exe',
      antigravity_ide_executable: 'Antigravity IDE executable',
      antigravity_ide_executable_desc:
        'Optional Antigravity IDE executable path. When switching Classic accounts, processes at this path are protected from termination.',
      antigravity_ide_executable_placeholder:
        'Example: C:\\Program Files\\Antigravity IDE\\Antigravity IDE.exe',
      antigravity_args: 'Antigravity launch arguments',
      antigravity_args_desc:
        'Optional arguments passed when launching Antigravity, such as --user-data-dir.',
      antigravity_args_placeholder: 'Example: --user-data-dir D:\\AntigravityProfile',
      antigravity_ide_args: 'Antigravity IDE launch arguments',
      antigravity_ide_args_desc:
        'Optional arguments passed when launching Antigravity IDE, such as --user-data-dir.',
      antigravity_ide_args_placeholder: 'Example: --user-data-dir D:\\AntigravityIdeProfile',
      detect_antigravity_args: 'Detect',
    },
    startup: {
      title: 'Startup',
      description: 'Control application launch behavior at system startup.',
      auto_startup: 'Start with system',
      auto_startup_desc: 'Launch at sign-in and keep the app in the system tray',
      macos_hint:
        'macOS requires a signed app for Login Items to work. If auto-start fails, please sign the app or enable it manually in System Settings.',
    },
    privacy: {
      title: 'Privacy',
      description: 'Control how your data is used to improve the application.',
      error_reporting: 'Error Reporting',
      error_reporting_desc:
        'Send anonymous error reports to help us improve the app. No personal data is collected.',
      telemetry: 'Performance Telemetry',
      telemetry_desc:
        'Share anonymous timing metrics and traces to diagnose slow account switching.',
      clarity: 'Microsoft Clarity',
      clarity_desc:
        'Share anonymous interaction diagnostics, heatmaps, and session replay to improve the app.',
      clarity_unavailable: 'Microsoft Clarity is not configured for this build.',
      restart_note: 'Some observability changes will take effect after restarting the application.',
    },
    notifications: {
      title: 'Notifications',
      description: 'Configure desktop alerts for account events.',
      quotaAlert: 'Low Quota Alerts',
      quotaAlertDesc: 'Get notified when a model quota drops below the set threshold',
      quotaThreshold: 'Alert Threshold',
      quotaThresholdDesc: 'Percentage below which to trigger an alert',
      saveFailed: 'Failed to save notification settings',
      thresholdSaveFailed: 'Failed to save threshold setting',
    },
    proxy: {
      title: 'Upstream Proxy',
      description: 'Configure a proxy for outgoing requests to Google/Gemini APIs.',
      enable: 'Enable Upstream Proxy',
      url: 'Proxy URL',
      timeout: 'Request Timeout (Seconds)',
    },
    modelMapping: {
      title: 'Model Mapping',
      description:
        'Map Claude Code models to Antigravity models. Optimize cost and speed by routing requests intelligently.',
      claudeKeyword: 'Claude Model (Keyword)',
      targetGemini: 'Target Gemini Model',
      addPlaceholderKey: 'e.g. op-3',
      addPlaceholderValue: 'e.g. gemini-3-flash',
      noMappings: 'No custom mappings defined.',
      mapsTo: 'Maps to',
      default: 'Default',
      restoreDefaults: 'Restore Defaults',
    },
    modelVisibility: {
      title: 'Model Visibility',
      description:
        "Control which models are visible in account cards. Hidden models won't appear in the quota display.",
      searchPlaceholder: 'Search models...',
      showAll: 'Show All',
      hideAll: 'Hide All',
      reset: 'Reset to Defaults',
      save: 'Save Changes',
      noModels: 'No models found',
      modelsShown: '{{visible}} of {{total}} models visible',
      quotaManagement: 'Quota Management',
      hidden: 'Hidden',
      noModelsFound: 'No models found',
      totalModels: 'Total',
      visibleModels: 'Visible',
      hiddenModels: 'Hidden',
      saving: 'Saving...',
    },
    providerGroupings: {
      title: 'Provider Groupings',
      description: 'Group models by provider for better organization',
      enabled: 'Enable Provider Groupings',
      models: '{{count}} models',
      avgLabel: 'avg',
      resetLabel: 'reset',
      overall: 'Overall',
      healthy: 'Healthy',
      degraded: 'Degraded',
      limited: 'Limited',
      critical: 'Critical',
    },

    examples: {
      title: 'Usage Examples',
      description: 'Example commands to call the local API proxy.',
      curl: 'cURL',
      python: 'Python',
      copy: 'Copy',
      copied: 'Copied!',
      openai_protocol: 'OpenAI Protocol',
      anthropic_protocol: 'Anthropic Protocol',
      openai_tools: 'Cursor, Windsurf, NextChat',
      anthropic_tools: 'Claude Code CLI',
      flash: 'Fast',
      pro: 'Pro',
      flash_preview: 'Preview',
      pro_high: 'Best',
      sonnet: 'Thinking',
      opus: 'Opus',
    },
    gateway: {
      title: 'API Proxy Service',
      description: 'Control the local API proxy server.',
      status_running: 'Running',
      status_stopped: 'Stopped',
      action_start: 'Start Service',
      action_stop: 'Stop Service',
      accounts_info: '{{count}} accounts available',
      port: 'Listen Port',
      port_hint: 'Default 8045, restart required to apply changes',
      timeout: 'Request Timeout',
      timeout_hint: 'Default 120s, range 30-600s',
      api_key: 'API Key',
      regenerate_key: 'Regenerate',
      regenerateConfirm: {
        title: 'Regenerate API Key?',
        description:
          'This will invalidate the current API key immediately. Any applications using the old key will stop working.',
        cancel: 'Cancel',
        confirm: 'Regenerate',
      },
      key_warning: 'Keep your API key secure. Do not share it.',
      auto_start: 'Auto Start with App',
      auto_start_desc: 'Start proxy service when application launches',
    },
    proxy_tab: 'Proxy',
    save: 'Save Settings',
  },
  toast: {
    backupSuccess: {
      title: 'Success',
      description: 'Account backup created successfully.',
    },
    backupError: {
      title: 'Error',
      description: 'Failed to create backup: {{error}}',
    },
    switchSuccess: {
      title: 'Success',
      description: 'Switched account successfully.',
    },
    switchError: {
      title: 'Error',
      description: 'Failed to switch account: {{error}}',
    },
    deleteSuccess: {
      title: 'Success',
      description: 'Account backup deleted successfully.',
    },
    deleteError: {
      title: 'Error',
      description: 'Failed to delete backup: {{error}}',
    },
  },
  cloud: {
    title: 'Accounts',
    description: 'Manage your Google Gemini account pool.',
    autoSwitch: 'Auto-Switch',
    providerGroupings: 'Provider Groupings',
    addAccount: 'Add Account',
    syncFromIde: 'Sync from IDE',
    checkQuota: 'Check Quota Now',
    polling: 'Polling triggered',
    globalQuota: 'Global Quota',
    layout: {
      auto: 'Auto',
      twoCol: '2 Columns',
      threeCol: '3 Columns',
      list: 'List',
      compact: 'Compact',
    },
    authDialog: {
      title: 'Add Google Account',
      description: 'To add an account, you need to authorize the application.',
      oauthClient: 'OAuth Client',
      oauthClientPlaceholder: 'Select OAuth client',
      openLogin: 'Open Login Page',
      authCode: 'Authorization Code',
      placeholder: 'Paste the code starting with 4/...',
      instruction:
        'Will open default browser for Google login. Copy the code from localhost page and paste here.',
      verify: 'Verify & Add',
    },
    card: {
      active: 'Active',
      use: 'Use',
      rateLimited: 'Rate Limited',
      validationRiskControlled: 'Risk / Rate Limited',
      validationOAuthReauthRequired: 'OAuth Re-auth Required',
      validationRequired: 'Verification Required',
      left: 'left',
      used: 'Used',
      unknown: 'Unknown User',
      actions: 'Actions',
      useAccount: 'Use Account',
      identityProfile: 'Identity Profile',
      refresh: 'Refresh Quota',
      delete: 'Delete Account',
      noQuota: 'No quota data',
      rateLimitedQuota: 'Rate Limited',
      resetPrefix: 'reset',
      resetTime: 'Reset time',
      resetUnknown: 'Unknown',
      gemini3Ready: 'Gemini 3 Ready',
      groupGoogleGemini: 'Google Gemini',
      groupAnthropicClaude: 'Anthropic Claude',
      proxy: 'Proxy',
      proxyPlaceholder: 'e.g. http://127.0.0.1:7890',
      proxySaved: 'Proxy saved',
      noProxy: 'No proxy',
      aiCredits: 'AI Credits',
      aiCreditsValue: '{{amount}} credits',
      creditsExpiry: 'expires {{date}}',
      modelVisibility: 'Model Visibility',
    },
    identity: {
      title: 'Identity Profile',
      loading: 'Loading...',
      generateAndBind: 'Create and Bind',
      captureAndBind: 'Capture and Bind Current',
      restoreOriginal: 'Restore Baseline',
      openFolder: 'Open Identity Storage',
      previewTitle: 'Generated Identity Preview',
      confirm: 'Confirm',
      cancel: 'Cancel',
      close: 'Close',
      currentStorage: 'Current Runtime Identity',
      accountBinding: 'Bound Account Identity',
      history: 'Identity History',
      noHistory: 'No identity history',
      current: 'Active',
      restore: 'Restore',
      generateSuccess: 'Identity created and bound',
      captureSuccess: 'Current identity captured and bound',
      restoreOriginalSuccess: 'Baseline identity restored',
      restoreVersionSuccess: 'Historical identity restored',
      deleteVersionSuccess: 'Historical identity deleted',
      openFolderSuccess: 'Identity storage opened',
      baseline: 'Baseline Identity',
    },
    list: {
      noAccounts: 'No cloud accounts added yet.',
      noFilteredAccounts: 'No accounts match the selected tiers.',
    },
    error: {
      loadFailed: 'Failed to load cloud accounts.',
      dataRepair: {
        title: 'Encrypted account data needs repair',
        description:
          'The app could not decrypt local account data. This usually means the data was created with a different encryption key or the local data is corrupted.',
        stepReLogin: 'Re-login or re-add the affected accounts first.',
        stepMacPrivacy:
          'On macOS, check Keychain/privacy prompts. If the app is unsigned or was re-signed, sign it again, move it to /Applications, then reopen it.',
        stepCheckGithub: 'Check the GitHub repository README for the latest troubleshooting steps.',
        stepOpenIssue: 'Search GitHub Issues for this error before clearing local account data.',
        openRepository: 'Open GitHub Repository',
        openIssues: 'Open GitHub Issues',
      },
    },
    toast: {
      syncSuccess: {
        title: 'Sync Successful',
        description: 'Imported {{email}} from IDE.',
      },
      syncFailed: {
        title: 'Sync Failed',
        description: 'No active account found in IDE database.',
      },
      addSuccess: 'Account added successfully!',
      addFailed: {
        title: 'Failed to add account',
      },
      quotaRefreshed: 'Quota refreshed',
      refreshFailed: 'Failed to refresh quota',
      pollFailed: 'Failed to poll quota for all accounts',
      switched: {
        title: 'Account switched!',
        description: 'Restarting Antigravity...',
      },
      switchFailed: 'Failed to switch account',
      deleted: 'Account deleted',
      deleteFailed: 'Failed to delete account',
      deleteConfirm: 'Are you sure you want to delete this account?',
      autoSwitchOn: 'Auto-Switch Enabled',
      autoSwitchOff: 'Auto-Switch Disabled',
      updateSettingsFailed: 'Failed to update settings',
      actionFailed: 'Action failed',
      startAuthFailed: 'Failed to start sign-in flow',
      refreshCreditsAvailable: 'AI credits: {{amount}}',
      refreshCreditsUnavailable: 'AI credits not available for this refresh.',
      batchRefreshSuccess: 'Successfully refreshed {{count}} accounts.',
      batchRefreshPartial: {
        title: 'Refresh completed with issues',
        description: 'Refreshed {{successful}} accounts, {{failed}} failed.',
      },
      batchDeleteSuccess: 'Successfully deleted {{count}} accounts.',
      batchDeletePartial: {
        title: 'Deletion completed with issues',
        description: 'Deleted {{successful}} accounts, {{failed}} failed.',
      },
    },
    batch: {
      selected: 'Selected {{count}}',
      delete: 'Delete Selected',
      refresh: 'Refresh Selected',
      selectAll: 'Select All',
      clear: 'Clear Selection',
      confirmDelete: 'Are you sure you want to delete {{count}} accounts?',
    },
    tierFilter: {
      all: 'All tiers',
      reset: 'Reset to all',
      selectedCount: '{{count}} tiers',
      unknown: 'Unknown',
    },
    sort: {
      recentlyUsed: 'Recently Used',
      quotaOverall: 'Overall Quota',
      quotaClaude: 'Claude Quota',
      quotaPro3: 'Pro3 Quota',
      quotaFlash: 'Flash Quota',
    },
    exportImport: {
      export: 'Export',
      import: 'Import',
      exportTitle: 'Export Accounts',
      exportDesc: 'Choose whether to include authentication tokens in the export file.',
      includeTokens: 'Include tokens (less secure)',
      stripTokens: 'Strip tokens (safer for sharing)',
      exportSuccess: 'Accounts exported successfully',
      importTitle: 'Import Accounts',
      importDesc: 'Select a previously exported JSON file.',
      importStrategy: 'Import Strategy',
      strategyMerge: 'Merge - Update existing, add new',
      strategyOverwrite: 'Overwrite - Replace all existing data',
      strategySkip: 'Skip - Only add new accounts',
      importSuccess: 'Imported {{imported}}, updated {{updated}}, skipped {{skipped}}',
      importErrors: 'Import completed with {{count}} error(s)',
      selectFile: 'Select File',
      importing: 'Importing...',
      fileTooLarge: 'File size exceeds 5MB limit',
      invalidJson: 'Invalid JSON file format',
      readFileFailed: 'Failed to read file',
    },
  },
  proxy: {
    title: 'API Proxy',
    description: 'Manage the local API proxy service.',
    save: 'Save Settings',
    copy: 'Copy',
    copied: 'Copied!',
    regenerate: 'Regenerate',
    regenerateConfirm: {
      title: 'Regenerate API Key?',
      description:
        'This will invalidate the current API key immediately. Any applications using the old key will stop working.',
      cancel: 'Cancel',
      confirm: 'Regenerate',
    },
    service: {
      title: 'Service Status',
      description: 'Control the local API proxy server.',
      running: 'Running',
      stopped: 'Stopped',
      start: 'Start Service',
      stop: 'Stop Service',
    },
    config: {
      port: 'Listen Port',
      timeout: 'Request Timeout',
      api_key: 'API Key',
      auto_start: 'Auto Start with App',
      auto_start_desc: 'Start proxy service when application launches',
      cloud_code_meta: 'Cloud Code metadata chunks',
      cloud_code_meta_desc:
        'Inject non-standard __cloudCodeMeta SSE chunks for legacy Cloud Code compatibility. Keep disabled for strict OpenAI clients.',
      local_access: 'Local network access:',
      select_ip: 'Select IP',
      no_token_warning: '⚠️ API key is not set. Access is open to everyone!',
      show_key: 'Show',
      hide_key: 'Hide',
    },
    mapping: {
      title: 'Model Mapping',
      description: 'Map Claude models to Gemini models for routing.',
      maps_to: 'Maps to',
      restore: 'Restore Defaults',
    },
    examples: {
      title: 'Usage Examples',
      description: 'Example commands to call the local API proxy.',
    },
  },
};
export default en;
