import type en from './en';

const fr = {
  appName: 'Antigravity Manager',
  common: {
    loading: 'Chargement...',
    error: 'Erreur',
    unknown: 'Inconnu',
    notAvailable: 'N/A',
    openMenu: 'Ouvrir le menu',
  },
  status: {
    checking: 'Verification du statut...',
    running: 'Antigravity fonctionne en arriere-plan',
    stopped: 'Service Antigravity arrete',
    services: 'Services',
    dashboard_title: 'Statut des services',
    open_dashboard: 'Ouvrir le statut des services',
    checking_short: 'Verification...',
    running_short: 'En cours',
    stopped_short: 'Arrete',
    all_running: 'Tous les services fonctionnent',
    all_stopped: 'Tous les services sont arretes',
    partial_running: '{{running}}/{{total}} services fonctionnent',
  },
  action: {
    stop: 'Arreter',
    start: 'Demarrer',
    switch: 'Basculer',
    deleteBackup: 'Supprimer la sauvegarde',
    backupCurrent: 'Sauvegarder le compte actuel',
    retry: 'Reessayer',
    details: 'Details',
    openLogs: 'Ouvrir le dossier des journaux',
  },
  update: {
    title: 'Mises a jour',
    checking: 'Verification...',
    checkNow: 'Rechercher des mises a jour',
    checkFailed: 'Impossible de rechercher des mises a jour',
    upToDate: 'Vous etes a jour.',
    unsupported:
      'La recherche automatique de mises a jour n est pas disponible sur cette plateforme.',
    available: {
      title: 'Mise a jour disponible',
      description: 'La version {{version}} est disponible sur GitHub.',
      download: 'Telecharger',
      downloading: 'Telechargement...',
      dismiss: 'Ignorer',
      macosUnsignedNote:
        'Cette version macOS n est pas officiellement signee. Si macOS bloque l app, suivez les etapes de signature manuelle dans le README GitHub ou les issues associees.',
    },
    downloaded: {
      title: 'Mise a jour prete',
      description: 'La version {{version}} a ete telechargee.',
      restart: 'Redemarrer',
    },
  },
  error: {
    generic: 'Une erreur inattendue s est produite.',
    detailsTitle: 'Details de l erreur',
    detailsDescription:
      'Les details d erreur du backend sont affiches ci-dessous. Ils peuvent inclure des chemins de fichiers locaux et des frames de pile.',
    keychainUnavailable: 'Le trousseau n est pas disponible.',
    keychainHint: {
      translocation:
        'Translocation d app macOS detectee. Deplacez l app vers /Applications puis rouvrez-la.',
      keychainDenied:
        'Acces au trousseau refuse. L app n est peut-etre pas signee ; consultez le README pour la solution de signature locale.',
      signNotarize: 'Utilisez une version signee et notarisee lorsqu elle est disponible.',
    },
    dataMigrationFailed: 'Impossible de dechiffrer les donnees de compte heritees.',
    dataMigrationHint: {
      relogin: 'Reconnectez-vous ou ajoutez de nouveau vos comptes.',
      clearData:
        'Si le probleme persiste, effacez les donnees de compte locales et reconnectez-vous.',
    },
    antigravityStorageJsonNotFound:
      'Le fichier storage.json d Antigravity est introuvable. Ouvrez l app Antigravity cible et connectez-vous une fois, puis reessayez de basculer.',
    antigravityProjectIdMissing:
      'Il manque un ID de projet Antigravity a ce compte. Cela peut arriver si le compte ne s est jamais connecte a l app Antigravity. Connectez-vous une fois dans Antigravity, puis revenez dans cet outil et reessayez.',
    antigravityDatabasePermissionDenied:
      'Le stockage de base de donnees Antigravity n est pas accessible en ecriture. Verifiez le dossier de donnees utilisateur Antigravity configure ou redemarrez Antigravity Manager apres avoir ouvert Antigravity une fois.',
    cloudAccountLoginExpired:
      'Les informations de connexion de ce compte cloud ont expire. Veuillez vous reconnecter.',
  },
  nav: {
    accounts: 'Comptes',
    proxy: 'Proxy API',
    settings: 'Parametres',
  },
  editionSelection: {
    title: 'Choisissez votre edition Antigravity',
    description:
      'Selectionnez la version d Antigravity que vous utilisez. Cela aide le Manager a se connecter a la bonne application.',
    edition1x: {
      name: 'Antigravity 1.x',
      description:
        'L application Antigravity originale. Choisissez ceci si vous utilisez l ancienne version.',
    },
    edition20: {
      name: 'Antigravity IDE',
      description:
        'Le nouvel Antigravity IDE (2.0). Choisissez ceci si vous utilisez la derniere version IDE.',
    },
    confirm: 'Continuer',
  },
  account: {
    current: 'Actuel',
    lastUsed: 'Derniere utilisation {{time}}',
    switchToAntigravity: 'Basculer vers Antigravity',
    switchToIde: 'Basculer vers Antigravity IDE',
  },
  home: {
    title: 'Comptes',
    description: 'Gerez vos comptes Google Gemini Antigravity.',
    noBackups: {
      title: 'Aucune sauvegarde trouvee',
      description: 'Creez une sauvegarde de votre compte Antigravity actuel pour commencer.',
      action: 'Sauvegarder le compte actuel',
    },
  },
  settings: {
    title: 'Parametres',
    description: 'Gerez les preferences de l application.',
    general: 'General',
    connection: 'Connexion',
    models: 'Modeles',
    appearance: {
      title: 'Apparence',
      description: 'Personnalisez l apparence d Antigravity Manager sur votre appareil.',
    },
    darkMode: 'Mode sombre',
    darkModeDescription: 'Activez le mode sombre pour un meilleur confort la nuit.',
    language: {
      title: 'Langue',
      description: 'Selectionnez votre langue preferee.',
      english: 'Anglais',
      chinese: 'Chinois (simplifie)',
      russian: 'Russe',
      vietnamese: 'Vietnamien',
      turkish: 'Turc',
      french: 'Français',
    },
    about: {
      title: 'A propos',
      description: 'Informations sur l application.',
    },
    version: 'Version',
    platform: 'Plateforme',
    license: 'Licence',
    openLogDir: 'Ouvrir',
    toast: {
      saved: {
        title: 'Parametres enregistres',
        description: 'Votre configuration a ete mise a jour.',
      },
      saveFailed: {
        title: 'Erreur lors de l enregistrement des parametres',
      },
    },
    account: {
      title: 'Parametres du compte',
      description: 'Configurez l actualisation et la synchronisation automatiques des comptes.',
      auto_refresh: 'Actualisation automatique du quota',
      auto_refresh_desc: 'Actualiser regulierement les informations de quota de tous les comptes',
      auto_sync: 'Synchronisation automatique du compte actuel',
      auto_sync_desc: 'Synchroniser regulierement les informations du compte actif',
      antigravity_executable: 'Executable Antigravity',
      antigravity_executable_desc:
        'Chemin facultatif utilise pour trouver les donnees du mode portable et lancer Antigravity.',
      antigravity_executable_placeholder:
        'Exemple : C:\\Program Files\\Antigravity\\Antigravity.exe',
      antigravity_ide_executable: 'Executable Antigravity IDE',
      antigravity_ide_executable_desc:
        'Chemin facultatif de l executable Antigravity IDE. Lors du basculement de comptes Classic, les processus a ce chemin sont proteges contre l arret.',
      antigravity_ide_executable_placeholder:
        'Exemple : C:\\Program Files\\Antigravity IDE\\Antigravity IDE.exe',
      antigravity_args: 'Arguments de lancement Antigravity',
      antigravity_args_desc:
        'Arguments facultatifs transmis au lancement d Antigravity, comme --user-data-dir.',
      antigravity_args_placeholder: 'Exemple : --user-data-dir D:\\AntigravityProfile',
      antigravity_ide_args: 'Arguments de lancement Antigravity IDE',
      antigravity_ide_args_desc:
        'Arguments facultatifs transmis au lancement d Antigravity IDE, comme --user-data-dir.',
      antigravity_ide_args_placeholder: 'Exemple : --user-data-dir D:\\AntigravityIdeProfile',
      detect_antigravity_args: 'Detecter',
    },
    startup: {
      title: 'Demarrage',
      description: 'Controlez le comportement de lancement au demarrage du systeme.',
      auto_startup: 'Demarrer avec le systeme',
      auto_startup_desc: 'Lancer a la connexion et garder l app dans la zone de notification',
      start_in_tray: 'Demarrer dans la zone de notification',
      start_in_tray_desc: "Demarrer l'application reduite dans la zone de notification",
      macos_hint:
        'macOS exige une app signee pour que les elements de connexion fonctionnent. Si le demarrage automatique echoue, signez l app ou activez-la manuellement dans les reglages systeme.',
    },
    privacy: {
      title: 'Confidentialite',
      description: 'Controlez l utilisation de vos donnees pour ameliorer l application.',
      error_reporting: 'Rapports d erreur',
      error_reporting_desc:
        'Envoyer des rapports d erreur anonymes pour nous aider a ameliorer l app. Aucune donnee personnelle n est collectee.',
      telemetry: 'Telemetrie de performance',
      telemetry_desc:
        'Partager des metriques et traces anonymes pour diagnostiquer les basculements de compte lents.',
      clarity: 'Microsoft Clarity',
      clarity_desc:
        'Partager des diagnostics d interaction anonymes, des heatmaps et des relectures de session pour ameliorer l app.',
      clarity_unavailable: 'Microsoft Clarity n est pas configure pour cette build.',
      restart_note:
        'Certaines modifications d observabilite prendront effet apres le redemarrage de l application.',
    },
    notifications: {
      title: 'Notifications',
      description: 'Configurez les alertes de bureau pour les evenements de compte.',
      quotaAlert: 'Alertes de quota faible',
      quotaAlertDesc:
        'Recevoir une notification quand le quota d un modele passe sous le seuil defini',
      quotaThreshold: 'Seuil d alerte',
      quotaThresholdDesc: 'Pourcentage en dessous duquel declencher une alerte',
      saveFailed: 'Echec de l enregistrement des parametres de notification',
      thresholdSaveFailed: 'Echec de l enregistrement du seuil',
      aiCreditsAlert: 'Alerte de credits IA faibles',
      aiCreditsAlertDesc:
        'Recevoir une notification quand le solde de credits IA atteint ou passe sous le seuil defini',
      aiCreditsThreshold: 'Seuil d alerte de credits IA',
      aiCreditsThresholdDesc: 'Montant de credits en dessous ou egal auquel declencher une alerte',
      aiCreditsThresholdSaveFailed: 'Echec de l enregistrement du seuil de credits IA',
    },
    proxy: {
      title: 'Proxy amont',
      description: 'Configurez un proxy pour les requetes sortantes vers les API Google/Gemini.',
      enable: 'Activer le proxy amont',
      url: 'URL du proxy',
      timeout: 'Delai de requete (secondes)',
    },
    modelMapping: {
      title: 'Mappage des modeles',
      description:
        'Mappez les modeles Claude Code vers les modeles Antigravity. Optimisez cout et vitesse en routant les requetes intelligemment.',
      claudeKeyword: 'Modele Claude (mot-cle)',
      targetGemini: 'Modele Gemini cible',
      addPlaceholderKey: 'ex. op-3',
      addPlaceholderValue: 'ex. gemini-3-flash',
      noMappings: 'Aucun mappage personnalise defini.',
      mapsTo: 'Mappe vers',
      default: 'Par defaut',
      restoreDefaults: 'Restaurer les valeurs par defaut',
    },
    modelVisibility: {
      title: 'Visibilite des modeles',
      description:
        'Controlez les modeles visibles dans les cartes de compte. Les modeles masques n apparaitront pas dans l affichage du quota.',
      searchPlaceholder: 'Rechercher des modeles...',
      showAll: 'Tout afficher',
      hideAll: 'Tout masquer',
      reset: 'Reinitialiser par defaut',
      save: 'Enregistrer les modifications',
      noModels: 'Aucun modele trouve',
      modelsShown: '{{visible}} sur {{total}} modeles visibles',
      quotaManagement: 'Gestion des quotas',
      hidden: 'Masque',
      noModelsFound: 'Aucun modele trouve',
      totalModels: 'Total',
      visibleModels: 'Visibles',
      hiddenModels: 'Masques',
      saving: 'Enregistrement...',
    },
    autoSwitchModels: {
      title: 'Auto-Switch Models Config',
      description:
        'Configure which models trigger auto-switch when depleted, and prioritize specific models when selecting the next active account.',
      searchPlaceholder: 'Search models...',
      noModels: 'No models found.',
      noModelsFound: 'No models found.',
      includeLabel: 'Include',
      priorityLabel: 'Priority',
      save: 'Save Config',
      saving: 'Saving...',
      saved: 'Auto-switch model configuration saved successfully.',
      saveFailed: 'Failed to save auto-switch model configuration.',
    },
    providerGroupings: {
      title: 'Groupements de fournisseurs',
      description: 'Regrouper les modeles par fournisseur pour une meilleure organisation',
      enabled: 'Activer les groupements de fournisseurs',
      models: '{{count}} modeles',
      avgLabel: 'moy.',
      resetLabel: 'reset',
      overall: 'Global',
      healthy: 'Sain',
      degraded: 'Degrade',
      limited: 'Limite',
      critical: 'Critique',
    },
    examples: {
      title: 'Exemples d utilisation',
      description: 'Exemples de commandes pour appeler le proxy API local.',
      curl: 'cURL',
      python: 'Python',
      copy: 'Copier',
      copied: 'Copie !',
      openai_protocol: 'Protocole OpenAI',
      anthropic_protocol: 'Protocole Anthropic',
      openai_tools: 'Cursor, Windsurf, NextChat',
      anthropic_tools: 'Claude Code CLI',
      flash: 'Rapide',
      pro: 'Pro',
      flash_preview: 'Apercu',
      pro_high: 'Meilleur',
      sonnet: 'Raisonnement',
      opus: 'Opus',
    },
    gateway: {
      title: 'Service proxy API',
      description: 'Controlez le serveur proxy API local.',
      status_running: 'En cours',
      status_stopped: 'Arrete',
      action_start: 'Demarrer le service',
      action_stop: 'Arreter le service',
      accounts_info: '{{count}} comptes disponibles',
      port: 'Port d ecoute',
      port_hint: 'Par defaut 8045, redemarrage requis pour appliquer les changements',
      timeout: 'Delai de requete',
      timeout_hint: 'Par defaut 120 s, plage 30-600 s',
      api_key: 'Cle API',
      regenerate_key: 'Regenerer',
      regenerateConfirm: {
        title: 'Regenerer la cle API ?',
        description:
          'Cela invalidera immediatement la cle API actuelle. Toute application utilisant l ancienne cle cessera de fonctionner.',
        cancel: 'Annuler',
        confirm: 'Regenerer',
      },
      key_warning: 'Gardez votre cle API en securite. Ne la partagez pas.',
      auto_start: 'Demarrage automatique avec l app',
      auto_start_desc: 'Demarrer le service proxy au lancement de l application',
    },
    proxy_tab: 'Proxy',
    save: 'Enregistrer les parametres',
  },
  toast: {
    backupSuccess: {
      title: 'Succes',
      description: 'Sauvegarde du compte creee avec succes.',
    },
    backupError: {
      title: 'Erreur',
      description: 'Echec de la creation de la sauvegarde : {{error}}',
    },
    switchSuccess: {
      title: 'Succes',
      description: 'Compte bascule avec succes.',
    },
    switchError: {
      title: 'Erreur',
      description: 'Echec du basculement de compte : {{error}}',
    },
    deleteSuccess: {
      title: 'Succes',
      description: 'Sauvegarde du compte supprimee avec succes.',
    },
    deleteError: {
      title: 'Erreur',
      description: 'Echec de la suppression de la sauvegarde : {{error}}',
    },
  },
  cloud: {
    title: 'Comptes',
    description: 'Gerez votre pool de comptes Google Gemini.',
    autoSwitch: 'Basculement auto',
    providerGroupings: 'Groupements de fournisseurs',
    addAccount: 'Ajouter un compte',
    syncFromIde: 'Synchroniser depuis l IDE',
    checkQuota: 'Verifier le quota maintenant',
    polling: 'Interrogation declenchee',
    globalQuota: 'Quota global',
    layout: {
      auto: 'Auto',
      twoCol: '2 colonnes',
      threeCol: '3 colonnes',
      list: 'Liste',
      compact: 'Compact',
    },
    authDialog: {
      title: 'Ajouter un compte Google',
      description: 'Pour ajouter un compte, vous devez autoriser l application.',
      oauthClient: 'Client OAuth',
      oauthClientPlaceholder: 'Selectionner un client OAuth',
      openLogin: 'Ouvrir la page de connexion',
      authCode: 'Code d autorisation',
      placeholder: 'Collez le code commencant par 4/...',
      instruction:
        'Le navigateur par defaut s ouvrira pour la connexion Google. Copiez le code depuis la page localhost et collez-le ici.',
      verify: 'Verifier et ajouter',
    },
    card: {
      active: 'Actif',
      use: 'Utiliser',
      rateLimited: 'Limite par le debit',
      validationRiskControlled: 'Risque / limite par le debit',
      validationOAuthReauthRequired: 'Reauthentification OAuth requise',
      validationRequired: 'Verification requise',
      left: 'restant',
      used: 'Utilise',
      unknown: 'Utilisateur inconnu',
      actions: 'Actions',
      useAccount: 'Utiliser le compte',
      identityProfile: 'Profil d identite',
      refresh: 'Actualiser le quota',
      delete: 'Supprimer le compte',
      noQuota: 'Aucune donnee de quota',
      rateLimitedQuota: 'Limite par le debit',
      resetPrefix: 'reset',
      resetTime: 'Heure de reinitialisation',
      resetUnknown: 'Inconnue',
      detailedQuota: 'Quota detaille',
      quotaGroupUnknown: 'Groupe de quota',
      gemini3Ready: 'Pret pour Gemini 3',
      groupGoogleGemini: 'Google Gemini',
      groupAnthropicClaude: 'Anthropic Claude',
      proxy: 'Proxy',
      proxyPlaceholder: 'ex. http://127.0.0.1:7890',
      proxySaved: 'Proxy enregistre',
      noProxy: 'Aucun proxy',
      aiCredits: 'Credits IA',
      aiCreditsValue: '{{amount}} credits',
      creditsExpiry: 'expire le {{date}}',
      modelVisibility: 'Visibilite des modeles',
    },
    identity: {
      title: 'Profil d identite',
      loading: 'Chargement...',
      generateAndBind: 'Creer et associer',
      captureAndBind: 'Capturer et associer l actuel',
      restoreOriginal: 'Restaurer la base',
      openFolder: 'Ouvrir le stockage d identite',
      previewTitle: 'Apercu de l identite generee',
      confirm: 'Confirmer',
      cancel: 'Annuler',
      close: 'Fermer',
      currentStorage: 'Identite d execution actuelle',
      accountBinding: 'Identite associee au compte',
      history: 'Historique des identites',
      noHistory: 'Aucun historique d identite',
      current: 'Actif',
      restore: 'Restaurer',
      generateSuccess: 'Identite creee et associee',
      captureSuccess: 'Identite actuelle capturee et associee',
      restoreOriginalSuccess: 'Identite de base restauree',
      restoreVersionSuccess: 'Identite historique restauree',
      deleteVersionSuccess: 'Identite historique supprimee',
      openFolderSuccess: 'Stockage d identite ouvert',
      baseline: 'Identite de base',
    },
    list: {
      noAccounts: 'Aucun compte cloud ajoute pour le moment.',
      noFilteredAccounts: 'Aucun compte ne correspond aux niveaux selectionnes.',
    },
    error: {
      loadFailed: 'Echec du chargement des comptes cloud.',
      dataRepair: {
        title: 'Les donnees de compte chiffrees doivent etre reparees',
        description:
          'L app n a pas pu dechiffrer les donnees de compte locales. Cela signifie generalement que les donnees ont ete creees avec une autre cle de chiffrement ou qu elles sont corrompues.',
        stepReLogin: 'Reconnectez-vous ou ajoutez de nouveau les comptes affectes d abord.',
        stepMacPrivacy:
          'Sur macOS, verifiez les invites du trousseau et de confidentialite. Si l app n est pas signee ou a ete resignee, signez-la de nouveau, deplacez-la vers /Applications, puis rouvrez-la.',
        stepCheckGithub:
          'Consultez le README du depot GitHub pour les dernieres etapes de depannage.',
        stepOpenIssue:
          'Recherchez cette erreur dans les GitHub Issues avant d effacer les donnees de compte locales.',
        openRepository: 'Ouvrir le depot GitHub',
        openIssues: 'Ouvrir les GitHub Issues',
      },
    },
    toast: {
      syncSuccess: {
        title: 'Synchronisation reussie',
        description: '{{email}} importe depuis l IDE.',
      },
      syncFailed: {
        title: 'Echec de la synchronisation',
        description: 'Aucun compte actif trouve dans la base de donnees IDE.',
      },
      addSuccess: 'Compte ajoute avec succes !',
      addFailed: {
        title: 'Echec de l ajout du compte',
      },
      quotaRefreshed: 'Quota actualise',
      refreshFailed: 'Echec de l actualisation du quota',
      pollFailed: 'Echec de l interrogation du quota pour tous les comptes',
      switched: {
        title: 'Compte bascule !',
        description: 'Redemarrage d Antigravity...',
      },
      switchFailed: 'Echec du basculement de compte',
      deleted: 'Compte supprime',
      deleteFailed: 'Echec de la suppression du compte',
      deleteConfirm: 'Voulez-vous vraiment supprimer ce compte ?',
      autoSwitchOn: 'Basculement auto active',
      autoSwitchOff: 'Basculement auto desactive',
      updateSettingsFailed: 'Echec de la mise a jour des parametres',
      actionFailed: 'Action echouee',
      startAuthFailed: 'Echec du demarrage du flux de connexion',
      refreshCreditsAvailable: 'Credits IA : {{amount}}',
      refreshCreditsUnavailable: 'Credits IA indisponibles pour cette actualisation.',
      batchRefreshSuccess: '{{count}} comptes actualises avec succes.',
      batchRefreshPartial: {
        title: 'Actualisation terminee avec des problemes',
        description: '{{successful}} comptes actualises, {{failed}} en echec.',
      },
      batchDeleteSuccess: '{{count}} comptes supprimes avec succes.',
      batchDeletePartial: {
        title: 'Suppression terminee avec des problemes',
        description: '{{successful}} comptes supprimes, {{failed}} en echec.',
      },
    },
    batch: {
      selected: '{{count}} selectionnes',
      delete: 'Supprimer la selection',
      refresh: 'Actualiser la selection',
      selectAll: 'Tout selectionner',
      clear: 'Effacer la selection',
      confirmDelete: 'Voulez-vous vraiment supprimer {{count}} comptes ?',
    },
    tierFilter: {
      all: 'Tous les niveaux',
      reset: 'Reinitialiser a tous',
      selectedCount: '{{count}} niveaux',
      unknown: 'Inconnu',
    },
    sort: {
      recentlyUsed: 'Recemment utilises',
      quotaOverall: 'Quota global',
      quotaClaude: 'Quota Claude',
      quotaPro3: 'Quota Pro3',
      quotaFlash: 'Quota Flash',
    },
    exportImport: {
      export: 'Exporter',
      import: 'Importer',
      exportTitle: 'Exporter les comptes',
      exportDesc:
        'Choisissez d inclure ou non les jetons d authentification dans le fichier exporte.',
      includeTokens: 'Inclure les jetons (moins securise)',
      stripTokens: 'Retirer les jetons (plus sur pour le partage)',
      exportSuccess: 'Comptes exportes avec succes',
      importTitle: 'Importer des comptes',
      importDesc: 'Selectionnez un fichier JSON exporte precedemment.',
      importStrategy: 'Strategie d importation',
      strategyMerge: 'Fusionner - mettre a jour l existant, ajouter le nouveau',
      strategyOverwrite: 'Ecraser - remplacer toutes les donnees existantes',
      strategySkip: 'Ignorer - ajouter seulement les nouveaux comptes',
      importSuccess: '{{imported}} importes, {{updated}} mis a jour, {{skipped}} ignores',
      importErrors: 'Importation terminee avec {{count}} erreur(s)',
      selectFile: 'Selectionner un fichier',
      importing: 'Importation...',
      fileTooLarge: 'La taille du fichier depasse la limite de 5 Mo',
      invalidJson: 'Format de fichier JSON invalide',
      readFileFailed: 'Echec de la lecture du fichier',
    },
  },
  proxy: {
    title: 'Proxy API',
    description: 'Gerez le service proxy API local.',
    save: 'Enregistrer les parametres',
    copy: 'Copier',
    copied: 'Copie !',
    regenerate: 'Regenerer',
    regenerateConfirm: {
      title: 'Regenerer la cle API ?',
      description:
        'Cela invalidera immediatement la cle API actuelle. Toute application utilisant l ancienne cle cessera de fonctionner.',
      cancel: 'Annuler',
      confirm: 'Regenerer',
    },
    service: {
      title: 'Statut du service',
      description: 'Controlez le serveur proxy API local.',
      running: 'En cours',
      stopped: 'Arrete',
      start: 'Demarrer le service',
      stop: 'Arreter le service',
      start_failed: 'Echec du demarrage du service',
      port_in_use_title: 'Port deja utilise',
      port_in_use_description:
        'Le port {{port}} est deja utilise par un autre processus. Fermez ce processus, ou modifiez le port d ecoute du proxy API dans les parametres puis reessayez.',
    },
    config: {
      port: 'Port d ecoute',
      timeout: 'Delai de requete',
      api_key: 'Cle API',
      auto_start: 'Demarrage automatique avec l app',
      auto_start_desc: 'Demarrer le service proxy au lancement de l application',
      cloud_code_meta: 'Blocs de metadonnees Cloud Code',
      cloud_code_meta_desc:
        'Injecter des blocs SSE __cloudCodeMeta non standard pour la compatibilite avec l ancien Cloud Code. Gardez desactive pour les clients OpenAI stricts.',
      local_access: 'Acces reseau local :',
      select_ip: 'Selectionner une IP',
      no_token_warning: 'La cle API n est pas definie. L acces est ouvert a tout le monde !',
      show_key: 'Afficher',
      hide_key: 'Masquer',
    },
    mapping: {
      title: 'Mappage des modeles',
      description: 'Mapper les modeles Claude vers les modeles Gemini pour le routage.',
      maps_to: 'Mappe vers',
      restore: 'Restaurer les valeurs par defaut',
    },
    examples: {
      title: 'Exemples d utilisation',
      description: 'Exemples de commandes pour appeler le proxy API local.',
    },
  },
} satisfies typeof en;

export default fr;
