const ru = {
  appName: 'Antigravity Manager',
  common: {
    loading: 'Загрузка...',
    error: 'Ошибка',
    unknown: 'Неизвестно',
    notAvailable: 'Н/Д',
    openMenu: 'Открыть меню',
  },
  status: {
    checking: 'Проверка статуса...',
    running: 'Antigravity работает в фоне',
    stopped: 'Служба Antigravity остановлена',
  },
  action: {
    stop: 'Стоп',
    start: 'Старт',
    switch: 'Переключить',
    deleteBackup: 'Удалить резервную копию',
    backupCurrent: 'Создать бэкап текущего',
    retry: 'Повторить',
    details: 'Подробности',
    openLogs: 'Открыть папку логов',
  },
  update: {
    title: 'Обновления',
    checking: 'Проверка...',
    checkNow: 'Проверить обновления',
    checkFailed: 'Не удалось проверить обновления',
    upToDate: 'У вас последняя версия.',
    unsupported: 'Проверка обновлений недоступна на этой платформе.',
    available: {
      title: 'Доступно обновление',
      description: 'Версия {{version}} доступна на GitHub.',
      download: 'Скачать',
      downloading: 'Скачивание...',
      dismiss: 'Закрыть',
      macosUnsignedNote:
        'Эта сборка macOS официально не подписана. Если macOS блокирует приложение, следуйте шагам ручной подписи в GitHub README или связанных issues.',
    },
    downloaded: {
      title: 'Обновление готово',
      description: 'Версия {{version}} загружена.',
      restart: 'Перезапустить',
    },
  },
  error: {
    generic: 'Произошла непредвиденная ошибка.',
    detailsTitle: 'Детали ошибки',
    detailsDescription:
      'Ниже показаны детали ошибки backend. Они могут содержать локальные пути и стек вызовов.',
    keychainUnavailable: 'Keychain недоступен.',
    keychainHint: {
      translocation:
        'Обнаружено App Translocation (macOS). Переместите приложение в /Applications и откройте заново.',
      keychainDenied:
        'Доступ к Keychain запрещен. Возможно, приложение не подписано. См. README для инструкции.',
      signNotarize: 'Пожалуйста, используйте подписанную версию приложения.',
    },
    dataMigrationFailed: 'Не удалось расшифровать данные старого аккаунта.',
    dataMigrationHint: {
      relogin: 'Пожалуйста, перезайдите в аккаунт или добавьте его заново.',
      clearData: 'Если ошибка сохраняется, очистите локальные данные и войдите снова.',
    },
    antigravityStorageJsonNotFound:
      'Файл Antigravity storage.json не найден. Откройте целевое приложение Antigravity и войдите один раз, затем повторите переключение.',
    antigravityProjectIdMissing:
      'У этого аккаунта отсутствует Antigravity project ID. Это может произойти, если аккаунт раньше не входил в приложение Antigravity. Войдите один раз в приложении Antigravity, затем вернитесь в этот инструмент и повторите переключение.',
    antigravityDatabasePermissionDenied:
      'Хранилище базы данных Antigravity недоступно для записи. Проверьте настроенный каталог Antigravity user-data или перезапустите Antigravity Manager после однократного открытия Antigravity.',
    cloudAccountLoginExpired:
      'Данные входа для этого облачного аккаунта устарели. Пожалуйста, войдите снова.',
  },
  nav: {
    accounts: 'Аккаунты',
    proxy: 'API Прокси',
    settings: 'Настройки',
  },
  editionSelection: {
    title: 'Выберите версию Antigravity',
    description:
      'Выберите, какую версию Antigravity вы используете. Это поможет менеджеру подключиться к правильному приложению.',
    edition1x: {
      name: 'Antigravity 1.x',
      description:
        'Оригинальное приложение Antigravity. Выберите это, если вы используете устаревшую версию.',
    },
    edition20: {
      name: 'Antigravity IDE',
      description:
        'Новый Antigravity IDE (2.0). Выберите это, если вы используете последнюю версию IDE.',
    },
    confirm: 'Продолжить',
  },
  account: {
    current: 'Текущий',
    lastUsed: 'Последнее использование {{time}}',
    switchToAntigravity: 'Переключиться на Antigravity',
    switchToIde: 'Переключиться на Antigravity IDE',
  },
  home: {
    title: 'Аккаунты',
    description: 'Управление вашими аккаунтами Antigravity Google Gemini.',
    noBackups: {
      title: 'Бэкапы не найдены',
      description: 'Создайте резервную копию вашего текущего аккаунта Antigravity, чтобы начать.',
      action: 'Создать бэкап текущего аккаунта',
    },
  },
  settings: {
    title: 'Настройки',
    description: 'Управление настройками приложения.',
    general: 'Общие',
    connection: 'Подключение',
    models: 'Модели',
    appearance: {
      title: 'Внешний вид',
      description: 'Настройте внешний вид Antigravity Manager.',
    },
    darkMode: 'Темная тема',
    darkModeDescription: 'Включить темную тему для комфортной работы ночью.',
    language: {
      title: 'Язык',
      description: 'Выберите язык интерфейса.',
      english: 'English',
      chinese: '中文 (简体)',
      russian: 'Русский',
      vietnamese: 'Вьетнамский',
      turkish: 'Турецкий',
      french: 'Французский',
    },
    about: {
      title: 'О программе',
      description: 'Информация о приложении.',
    },
    version: 'Версия',
    platform: 'Платформа',
    license: 'Лицензия',
    openLogDir: 'Открыть',
    toast: {
      saved: {
        title: 'Настройки сохранены',
        description: 'Конфигурация обновлена.',
      },
      saveFailed: {
        title: 'Ошибка сохранения настроек',
      },
    },
    account: {
      title: 'Настройки аккаунта',
      description: 'Настройка автоматического обновления и синхронизации.',
      auto_refresh: 'Автообновление квот',
      auto_refresh_desc: 'Периодически обновлять информацию о квотах для всех аккаунтов',
      auto_sync: 'Автосинхронизация текущего',
      auto_sync_desc: 'Периодически синхронизировать активный аккаунт',
      antigravity_executable: 'Файл запуска Antigravity',
      antigravity_executable_desc:
        'Необязательный путь для поиска данных portable mode и запуска Antigravity.',
      antigravity_executable_placeholder:
        'Например: C:\\Program Files\\Antigravity\\Antigravity.exe',
      antigravity_ide_executable: 'Файл запуска Antigravity IDE',
      antigravity_ide_executable_desc:
        'Необязательный путь к Antigravity IDE. При переключении аккаунтов Classic процессы по этому пути защищаются от завершения.',
      antigravity_ide_executable_placeholder:
        'Например: C:\\Program Files\\Antigravity IDE\\Antigravity IDE.exe',
      antigravity_args: 'Аргументы запуска Antigravity',
      antigravity_args_desc: 'Необязательные аргументы запуска, например --user-data-dir.',
      antigravity_args_placeholder: 'Например: --user-data-dir D:\\AntigravityProfile',
      antigravity_ide_args: 'Аргументы запуска Antigravity IDE',
      antigravity_ide_args_desc:
        'Необязательные аргументы запуска Antigravity IDE, например --user-data-dir.',
      antigravity_ide_args_placeholder: 'Например: --user-data-dir D:\\AntigravityIdeProfile',
      detect_antigravity_args: 'Найти',
    },
    startup: {
      title: 'Автозагрузка',
      description: 'Управление запуском приложения при старте системы.',
      auto_startup: 'Запускать вместе с системой',
      auto_startup_desc: 'Запускать при входе и сворачивать в трей',
      start_in_tray: 'Запускать в трее',
      start_in_tray_desc: 'Запускать приложение свернутым в системный трей',
      macos_hint:
        'macOS требует подписанное приложение для работы элементов входа. Если автозапуск не работает, подпишите приложение или включите его вручную в системных настройках.',
    },
    privacy: {
      title: 'Конфиденциальность',
      description: 'Управление использованием данных для улучшения приложения.',
      error_reporting: 'Отчеты об ошибках',
      error_reporting_desc:
        'Отправляйте анонимные отчеты об ошибках, чтобы помочь нам улучшить приложение. Личные данные не собираются.',
      telemetry: 'Телеметрия производительности',
      telemetry_desc:
        'Отправлять анонимные метрики времени и трассировки для диагностики медленного переключения аккаунтов.',
      clarity: 'Microsoft Clarity',
      clarity_desc:
        'Отправлять анонимную диагностику взаимодействия, тепловые карты и записи сеансов для улучшения приложения.',
      clarity_unavailable: 'Microsoft Clarity не настроен для этой сборки.',
      restart_note:
        'Некоторые изменения наблюдаемости вступят в силу после перезапуска приложения.',
    },
    notifications: {
      title: 'Уведомления',
      description: 'Настройте уведомления о событиях аккаунтов.',
      quotaAlert: 'Уведомления о низкой квоте',
      quotaAlertDesc: 'Получайте уведомления, когда квота модели падает ниже установленного порога',
      quotaThreshold: 'Порог уведомления',
      quotaThresholdDesc: 'Процент, ниже которого срабатывает уведомление',
      saveFailed: 'Не удалось сохранить настройки уведомлений',
      thresholdSaveFailed: 'Не удалось сохранить порог уведомления',
      aiCreditsAlert: 'Уведомление о низком балансе AI-кредитов',
      aiCreditsAlertDesc:
        'Получайте уведомления, когда баланс AI-кредитов достигает или опускается ниже установленного значения',
      aiCreditsThreshold: 'Порог уведомления об AI-кредитах',
      aiCreditsThresholdDesc:
        'Количество кредитов, при достижении которого срабатывает уведомление',
      aiCreditsThresholdSaveFailed: 'Не удалось сохранить порог AI-кредитов',
    },
    proxy: {
      title: 'Верхнеуровневый прокси',
      description: 'Настроить прокси для исходящих запросов к Google/Gemini API.',
      enable: 'Включить прокси',
      url: 'URL прокси',
      timeout: 'Тайм-аут запроса (сек)',
    },
    modelMapping: {
      title: 'Маппинг моделей',
      description:
        'Сопоставьте модели Claude Code с моделями Antigravity. Оптимизируйте затраты и скорость, разумно маршрутизируя запросы.',
      claudeKeyword: 'Модель Claude (Ключевое слово)',
      targetGemini: 'Целевая модель Gemini',
      addPlaceholderKey: 'например, op-3',
      addPlaceholderValue: 'например, gemini-3-flash',
      noMappings: 'Нет пользовательских сопоставлений.',
      mapsTo: 'Мапится в',
      default: 'По умолчанию',
      restoreDefaults: 'Сбросить по умолчанию',
    },
    modelVisibility: {
      title: 'Видимость моделей',
      description:
        'Управляйте тем, какие модели отображаются в карточках аккаунтов. Скрытые модели не будут показаны в отображении квот.',
      searchPlaceholder: 'Поиск моделей...',
      showAll: 'Показать все',
      hideAll: 'Скрыть все',
      reset: 'Сбросить по умолчанию',
      save: 'Сохранить изменения',
      noModels: 'Модели не найдены',
      modelsShown: '{{visible}} из {{total}} моделей видно',
      quotaManagement: 'Управление квотами',
      hidden: 'Скрыто',
      noModelsFound: 'Модели не найдены',
      totalModels: 'Всего',
      visibleModels: 'Видно',
      hiddenModels: 'Скрыто',
      saving: 'Сохранение...',
    },
    autoSwitchModels: {
      title: 'Настройка автосвапа моделей',
      description:
        'Настройте, какие модели вызывают автосвап при исчерпании лимитов, и какие модели приоритетны при выборе следующего аккаунта.',
      searchPlaceholder: 'Поиск моделей...',
      noModels: 'Модели не найдены.',
      noModelsFound: 'Модели не найдены.',
      includeLabel: 'Включить',
      priorityLabel: 'Приоритет',
      save: 'Сохранить настройки',
      saving: 'Сохранение...',
      saved: 'Настройки автосвапа успешно сохранены.',
      saveFailed: 'Не удалось сохранить настройки автосвапа.',
    },
    providerGroupings: {
      title: 'Группировка провайдеров',
      description: 'Группировка моделей по провайдерам для лучшей организации',
      enabled: 'Включить группировку провайдеров',
      models: '{{count}} моделей',
      avgLabel: 'сред.',
      resetLabel: 'сброс',
      overall: 'Общее',
      healthy: 'Исправно',
      degraded: 'Снижено',
      limited: 'Ограничено',
      critical: 'Критично',
    },
    examples: {
      title: 'Примеры использования',
      description: 'Примеры команд для вызова локального API прокси.',
      curl: 'cURL',
      python: 'Python',
      copy: 'Копировать',
      copied: 'Скопировано!',
      openai_protocol: 'Протокол OpenAI',
      anthropic_protocol: 'Протокол Anthropic',
      openai_tools: 'Cursor, Windsurf, NextChat',
      anthropic_tools: 'Claude Code CLI',
      flash: 'Быстрый (Flash)',
      pro: 'Про (Pro)',
      flash_preview: 'Превью (Flash Preview)',
      pro_high: 'Лучший (Pro High)',
      sonnet: 'Мыслящий (Sonnet)',
      opus: 'Opus',
    },
    gateway: {
      title: 'Служба API Прокси',
      description: 'Управление локальным прокси-сервером API.',
      status_running: 'Запущено',
      status_stopped: 'Остановлено',
      action_start: 'Запустить службу',
      action_stop: 'Остановить службу',
      accounts_info: '{{count}} аккаунтов доступно',
      port: 'Порт прослушивания',
      port_hint: 'По умолчанию 8045, требуется перезапуск для применения',
      timeout: 'Тайм-аут запроса',
      timeout_hint: 'По умолчанию 120с, диапазон 30-600с',
      api_key: 'API Ключ',
      regenerate_key: 'Перегенерировать',
      regenerateConfirm: {
        title: 'Перегенерировать API ключ?',
        description:
          'Это немедленно сделает текущий ключ недействительным. Все приложения, использующие старый ключ, перестанут работать.',
        cancel: 'Отмена',
        confirm: 'Перегенерировать',
      },
      key_warning: 'Держите ваш API ключ в секрете. Не передавайте его никому.',
      auto_start: 'Автозапуск с приложением',
      auto_start_desc: 'Запускать прокси-службу при старте приложения',
    },
    proxy_tab: 'Прокси',
    save: 'Сохранить настройки',
  },
  toast: {
    backupSuccess: {
      title: 'Успешно',
      description: 'Бэкап аккаунта создан.',
    },
    backupError: {
      title: 'Ошибка',
      description: 'Не удалось создать бэкап: {{error}}',
    },
    switchSuccess: {
      title: 'Успешно',
      description: 'Аккаунт переключен.',
    },
    switchError: {
      title: 'Ошибка',
      description: 'Не удалось переключить аккаунт: {{error}}',
    },
    deleteSuccess: {
      title: 'Успешно',
      description: 'Бэкап удален.',
    },
    deleteError: {
      title: 'Ошибка',
      description: 'Не удалось удалить бэкап: {{error}}',
    },
  },
  cloud: {
    title: 'Аккаунты',
    description: 'Управление пулом аккаунтов Google Gemini.',
    autoSwitch: 'Авто-переключение',
    providerGroupings: 'Группировка по провайдерам',
    addAccount: 'Добавить аккаунт',
    syncFromIde: 'Синхр. из IDE',
    checkQuota: 'Проверить квоту',
    polling: 'Опрос запущен',
    globalQuota: 'Глобальная квота',
    layout: {
      auto: 'Авто',
      twoCol: '2 колонки',
      threeCol: '3 колонки',
      list: 'Список',
      compact: 'Компактный',
    },
    authDialog: {
      title: 'Добавить Google Аккаунт',
      description: 'Для добавления аккаунта необходимо авторизовать приложение.',
      oauthClient: 'OAuth клиент',
      oauthClientPlaceholder: 'Выберите OAuth клиент',
      openLogin: 'Открыть страницу входа',
      authCode: 'Код авторизации',
      placeholder: 'Вставьте код, начинающийся с 4/...',
      instruction:
        'Откроется браузер для входа в Google. Скопируйте код со страницы localhost и вставьте сюда.',
      verify: 'Проверить и добавить',
    },
    card: {
      active: 'Активен',
      use: 'Использовать',
      rateLimited: 'Лимит исчерпан',
      validationRiskControlled: 'Риск / Ограничение',
      validationOAuthReauthRequired: 'Требуется повторный OAuth',
      validationRequired: 'Требуется проверка',
      left: 'ост.',
      used: 'Исп.',
      unknown: 'Неизвестный',
      actions: 'Действия',
      useAccount: 'Использовать этот аккаунт',
      identityProfile: 'Профиль идентичности',
      refresh: 'Обновить квоту',
      delete: 'Удалить аккаунт',
      noQuota: 'Нет данных',
      rateLimitedQuota: 'Лимит исчерпан',
      resetPrefix: 'Сброс',
      resetTime: 'Время сброса',
      resetUnknown: 'Неизвестно',
      detailedQuota: 'Подробная квота',
      quotaGroupUnknown: 'Группа квот',
      gemini3Ready: 'Gemini 3 готов',
      groupGoogleGemini: 'Google Gemini',
      groupAnthropicClaude: 'Anthropic Claude',
      proxy: 'Прокси',
      proxyPlaceholder: 'напр. http://127.0.0.1:7890',
      proxySaved: 'Прокси сохранён',
      noProxy: 'Без прокси',
      aiCredits: 'AI Кредиты',
      aiCreditsValue: '{{amount}} кредитов',
      creditsExpiry: 'истекает {{date}}',
      modelVisibility: 'Видимость моделей',
    },
    identity: {
      title: 'Профиль идентичности',
      loading: 'Загрузка...',
      generateAndBind: 'Создать и привязать',
      captureAndBind: 'Считать текущий и привязать',
      restoreOriginal: 'Восстановить базовый профиль',
      openFolder: 'Открыть хранилище профилей',
      previewTitle: 'Предпросмотр сгенерированного профиля',
      confirm: 'Подтвердить',
      cancel: 'Отмена',
      close: 'Закрыть',
      currentStorage: 'Текущий профиль окружения',
      accountBinding: 'Профиль, привязанный к аккаунту',
      history: 'История профилей',
      noHistory: 'История профилей пуста',
      current: 'Активный',
      restore: 'Восстановить',
      generateSuccess: 'Профиль создан и привязан',
      captureSuccess: 'Текущий профиль считан и привязан',
      restoreOriginalSuccess: 'Базовый профиль восстановлен',
      restoreVersionSuccess: 'Исторический профиль восстановлен',
      deleteVersionSuccess: 'Исторический профиль удален',
      openFolderSuccess: 'Хранилище профилей открыто',
      baseline: 'Базовый профиль',
    },
    list: {
      noAccounts: 'Нет добавленных облачных аккаунтов.',
      noFilteredAccounts: 'Нет аккаунтов для выбранных уровней.',
    },
    error: {
      loadFailed: 'Не удалось загрузить аккаунты.',
      dataRepair: {
        title: 'Зашифрованные данные аккаунта требуют восстановления',
        description:
          'Приложение не смогло расшифровать локальные данные аккаунта. Обычно это означает, что данные были созданы другим ключом шифрования или локальные данные повреждены.',
        stepReLogin: 'Сначала войдите снова или заново добавьте затронутые аккаунты.',
        stepMacPrivacy:
          'На macOS проверьте запросы Keychain/конфиденциальности. Если приложение не подписано или было переподписано, подпишите его снова, переместите в /Applications и откройте заново.',
        stepCheckGithub:
          'Проверьте README в репозитории GitHub на наличие актуальных шагов диагностики.',
        stepOpenIssue:
          'Перед очисткой локальных данных аккаунтов поищите эту ошибку в GitHub Issues.',
        openRepository: 'Открыть репозиторий GitHub',
        openIssues: 'Открыть GitHub Issues',
      },
    },
    toast: {
      syncSuccess: {
        title: 'Синхронизация успешна',
        description: 'Импортирован {{email}} из IDE.',
      },
      syncFailed: {
        title: 'Синхронизация не удалась',
        description: 'В базе данных IDE не найдено активных аккаунтов.',
      },
      addSuccess: 'Аккаунт успешно добавлен!',
      addFailed: {
        title: 'Не удалось добавить аккаунт',
      },
      quotaRefreshed: 'Квота обновлена',
      refreshFailed: 'Не удалось обновить квоту',
      pollFailed: 'Не удалось опросить квоты всех аккаунтов',
      switched: {
        title: 'Аккаунт переключен!',
        description: 'Перезапуск Antigravity...',
      },
      switchFailed: 'Не удалось переключить аккаунт',
      deleted: 'Аккаунт удален',
      deleteFailed: 'Не удалось удалить аккаунт',
      deleteConfirm: 'Вы уверены, что хотите удалить этот аккаунт?',
      autoSwitchOn: 'Авто-переключение включено',
      autoSwitchOff: 'Авто-переключение выключено',
      updateSettingsFailed: 'Не удалось обновить настройки',
      actionFailed: 'Не удалось выполнить действие',
      startAuthFailed: 'Не удалось запустить процесс входа',
      refreshCreditsAvailable: 'AI кредиты: {{amount}}',
      refreshCreditsUnavailable: 'AI кредиты недоступны для этого обновления.',
      batchRefreshSuccess: 'Успешно обновлено {{count}} аккаунтов.',
      batchRefreshPartial: {
        title: 'Обновление завершено с проблемами',
        description: 'Обновлено {{successful}} аккаунтов, {{failed}} с ошибкой.',
      },
      batchDeleteSuccess: 'Успешно удалено {{count}} аккаунтов.',
      batchDeletePartial: {
        title: 'Удаление завершено с проблемами',
        description: 'Удалено {{successful}} аккаунтов, {{failed}} с ошибкой.',
      },
    },
    batch: {
      selected: 'Выбрано {{count}}',
      delete: 'Удалить выбранные',
      refresh: 'Обновить выбранные',
      selectAll: 'Выбрать все',
      clear: 'Снять выделение',
      confirmDelete: 'Вы уверены, что хотите удалить {{count}} аккаунтов?',
    },
    tierFilter: {
      all: 'Все уровни',
      reset: 'Сбросить',
      selectedCount: '{{count}} уровня',
      unknown: 'Неизвестно',
    },
    sort: {
      recentlyUsed: 'Недавние',
      quotaOverall: 'Общая квота',
      quotaClaude: 'Квота Claude',
      quotaPro3: 'Квота Pro3',
      quotaFlash: 'Квота Flash',
    },
    exportImport: {
      export: 'Экспорт',
      import: 'Импорт',
      exportTitle: 'Экспорт аккаунтов',
      exportDesc: 'Выберите, включать ли токены аутентификации в файл экспорта.',
      includeTokens: 'Включить токены (менее безопасно)',
      stripTokens: 'Удалить токены (безопаснее для обмена)',
      exportSuccess: 'Аккаунты успешно экспортированы',
      importTitle: 'Импорт аккаунтов',
      importDesc: 'Выберите ранее экспортированный JSON файл.',
      importStrategy: 'Стратегия импорта',
      strategyMerge: 'Объединить - Обновить существующие, добавить новые',
      strategyOverwrite: 'Перезаписать - Заменить все существующие данные',
      strategySkip: 'Пропустить - Добавить только новые аккаунты',
      importSuccess: 'Импортировано {{imported}}, обновлено {{updated}}, пропущено {{skipped}}',
      importErrors: 'Импорт завершён с {{count}} ошибкой(ами)',
      selectFile: 'Выбрать файл',
      importing: 'Импорт...',
      fileTooLarge: 'Размер файла превышает лимит в 5 МБ',
      invalidJson: 'Некорректный формат JSON-файла',
      readFileFailed: 'Не удалось прочитать файл',
    },
  },
  proxy: {
    title: 'API Прокси',
    description: 'Управление локальным прокси-сервером API.',
    save: 'Сохранить',
    copy: 'Копировать',
    copied: 'Скопировано!',
    regenerate: 'Перегенерировать',
    regenerateConfirm: {
      title: 'Перегенерировать API ключ?',
      description:
        'Это немедленно сделает текущий ключ недействительным. Все приложения, использующие старый ключ, перестанут работать.',
      cancel: 'Отмена',
      confirm: 'Перегенерировать',
    },
    service: {
      title: 'Статус сервиса',
      description: 'Управление локальным сервером.',
      running: 'Работает',
      stopped: 'Остановлен',
      start: 'Запустить',
      stop: 'Остановить',
      start_failed: 'Не удалось запустить сервис',
      port_in_use_title: 'Порт уже используется',
      port_in_use_description:
        'Порт {{port}} уже используется другим процессом. Закройте этот процесс или измените порт API прокси в настройках и повторите попытку.',
    },
    config: {
      port: 'Порт',
      timeout: 'Тайм-аут',
      api_key: 'API Ключ',
      auto_start: 'Автозапуск',
      auto_start_desc: 'Запускать прокси при старте приложения',
      local_access: 'Доступ из локальной сети:',
      select_ip: 'Выбрать IP',
      no_token_warning: '⚠️ API ключ не установлен. Доступ открыт всем!',
      show_key: 'Показать',
      hide_key: 'Скрыть',
    },
    mapping: {
      title: 'Маппинг моделей',
      description: 'Настройка маршрутизации моделей.',
      maps_to: '->',
      restore: 'Сброс',
    },
    examples: {
      title: 'Примеры',
      description: 'Примеры использования локального прокси.',
    },
  },
};
export default ru;
