const tr = {
  appName: 'Antigravity Manager',
  common: {
    loading: 'Yükleniyor...',
    error: 'Hata',
    unknown: 'Bilinmeyen',
    notAvailable: 'Yok',
    openMenu: 'Menüyü aç',
  },
  status: {
    checking: 'Durum kontrol ediliyor...',
    running: 'Antigravity arka planda çalışıyor',
    stopped: 'Antigravity hizmeti durduruldu',
  },
  action: {
    stop: 'Durdur',
    start: 'Başlat',
    switch: 'Değiştir',
    deleteBackup: 'Yedeği Sil',
    backupCurrent: 'Mevcut Hesabı Yedekle',
    retry: 'Yeniden Dene',
    openLogs: 'Log Klasörünü Aç',
  },
  error: {
    generic: 'Beklenmeyen bir hata oluştu.',
    keychainUnavailable: 'Anahtar Zinciri (Keychain) kullanılamıyor.',
    keychainHint: {
      translocation:
        'macOS App Translocation algılandı. Uygulamayı /Applications klasörüne taşıyıp yeniden açın.',
      keychainDenied:
        'Anahtar Zinciri erişimi reddedildi. Uygulama imzalanmamış olabilir; kendi kendinize imzalama yöntemi için README dosyasına bakın.',
      signNotarize: 'Mümkünse lütfen imzalanmış ve noter onaylı bir sürüm kullanın.',
    },
    dataMigrationFailed: 'Eski hesap verilerinin şifresi çözülemedi.',
    dataMigrationHint: {
      relogin: 'Lütfen yeniden giriş yapın veya hesaplarınızı tekrar ekleyin.',
      clearData: 'Sorun devam ederse yerel hesap verilerini temizleyip tekrar giriş yapın.',
    },
  },
  nav: {
    accounts: 'Hesaplar',
    proxy: 'API Proxy',
    settings: 'Ayarlar',
  },
  editionSelection: {
    title: 'Antigravity Sürümünüzü Seçin',
    description: 'Kullandığınız Antigravity sürümünü seçin. Bu, Manager\'ın doğru uygulamaya bağlanmasını sağlar.',
    edition1x: {
      name: 'Antigravity 1.x',
      description: 'Orijinal Antigravity uygulaması. Eski sürümü kullanıyorsanız bunu seçin.',
    },
    edition20: {
      name: 'Antigravity IDE',
      description: 'Yeni Antigravity IDE (2.0). En son IDE sürümünü kullanıyorsanız bunu seçin.',
    },
    confirm: 'Devam Et',
  },
  account: {
    current: 'Mevcut',
    lastUsed: 'Son kullanım: {{time}}',
  },
  home: {
    title: 'Hesaplar',
    description: 'Antigravity Google Gemini hesaplarınızı yönetin.',
    noBackups: {
      title: 'Yedek bulunamadı',
      description: 'Başlamak için mevcut Antigravity hesabınızın bir yedeğini oluşturun.',
      action: 'Mevcut Hesabı Yedekle',
    },
  },
  settings: {
    title: 'Ayarlar',
    description: 'Uygulama tercihlerini yönetin.',
    general: 'Genel',
    connection: 'Bağlantı',
    models: 'Modeller',
    appearance: {
      title: 'Görünüm',
      description: "Antigravity Manager'ın cihazınızda nasıl görüneceğini özelleştirin.",
    },
    darkMode: 'Karanlık Mod',
    darkModeDescription: 'Gece daha iyi bir görünüm için karanlık modu etkinleştirin.',
    language: {
      title: 'Dil',
      description: 'Tercih ettiğiniz dili seçin.',
      english: 'İngilizce (English)',
      chinese: 'Çince (Basitleştirilmiş)',
      russian: 'Rusça',
      vietnamese: 'Vietnamca',
      turkish: 'Türkçe',
    },
    ideEdition: {
      title: 'Antigravity Sürümü',
      description: 'Kullandığınız Antigravity sürümünü seçin.',
      placeholder: 'Sürüm seçin',
      edition1x: 'Antigravity 1.x',
      edition20: 'Antigravity IDE',
    },
    about: {
      title: 'Hakkında',
      description: 'Uygulama bilgileri.',
    },
    version: 'Sürüm',
    platform: 'Platform',
    license: 'Lisans',
    openLogDir: 'Aç',
    toast: {
      saved: {
        title: 'Ayarlar kaydedildi',
        description: 'Yapılandırmanız güncellendi.',
      },
      saveFailed: {
        title: 'Ayarlar kaydedilirken hata oluştu',
      },
    },
    account: {
      title: 'Hesap Ayarları',
      description: 'Otomatik hesap yenileme ve eşitleme ayarlarını yapılandırın.',
      auto_refresh: 'Kotayı Otomatik Yenile',
      auto_refresh_desc: 'Tüm hesaplar için kota bilgilerini periyodik olarak yenile',
      auto_sync: 'Mevcut Hesabı Otomatik Eşitle',
      auto_sync_desc: 'Aktif hesap bilgilerini periyodik olarak eşitle',
    },
    startup: {
      title: 'Başlangıç',
      description: 'Sistem başlangıcında uygulamanın nasıl davranacağını kontrol edin.',
      auto_startup: 'Sistemle birlikte başlat',
      auto_startup_desc: 'Oturum açıldığında başlat ve sistem tepsisinde tut',
      macos_hint:
        'macOS, Oturum Açma Öğelerinin çalışması için imzalanmış bir uygulama gerektirir. Otomatik başlatma başarısız olursa, lütfen uygulamayı imzalayın veya Sistem Ayarlarından manuel olarak etkinleştirin.',
    },
    privacy: {
      title: 'Gizlilik',
      description: 'Verilerinizin uygulamayı geliştirmek için nasıl kullanılacağını kontrol edin.',
      error_reporting: 'Hata Raporlama',
      error_reporting_desc:
        'Uygulamayı geliştirmemize yardımcı olmak için anonim hata raporları gönderin. Hiçbir kişisel veri toplanmaz.',
      restart_note:
        'Hata raporlama değişiklikleri, uygulamayı yeniden başlattıktan sonra geçerli olacaktır.',
    },
    notifications: {
      title: 'Bildirimler',
      description: 'Hesap olayları için masaüstü uyarılarını yapılandırın.',
      quotaAlert: 'Düşük Kota Uyarıları',
      quotaAlertDesc: 'Bir model kotası belirlenen eşiğin altına düştüğünde bildirim alın',
      quotaThreshold: 'Uyarı Eşiği',
      quotaThresholdDesc: 'Uyarının tetikleneceği yüzde değeri',
      saveFailed: 'Bildirim ayarları kaydedilemedi',
      thresholdSaveFailed: 'Eşik ayarı kaydedilemedi',
    },
    proxy: {
      title: 'Üst Akış (Upstream) Proxy',
      description: "Google/Gemini API'lerine giden istekler için bir proxy yapılandırın.",
      enable: "Üst Akış Proxy'sini Etkinleştir",
      url: "Proxy URL'si",
      timeout: 'İstek Zaman Aşımı (Saniye)',
    },
    modelMapping: {
      title: 'Model Eşleme',
      description:
        'Claude Code modellerini Antigravity modelleriyle eşleyin. İstekleri akıllıca yönlendirerek maliyeti ve hızı optimize edin.',
      claudeKeyword: 'Claude Modeli (Anahtar Kelime)',
      targetGemini: 'Hedef Gemini Modeli',
      addPlaceholderKey: 'örn. op-3',
      addPlaceholderValue: 'örn. gemini-3-flash',
      noMappings: 'Özel eşleme tanımlanmadı.',
      mapsTo: 'Şu modele eşlenir:',
      default: 'Varsayılan',
      restoreDefaults: 'Varsayılanlara Sıfırla',
    },
    modelVisibility: {
      title: 'Model Görünürlüğü',
      description:
        'Hesap kartlarında hangi modellerin görüneceğini kontrol edin. Gizli modeller kota ekranında görünmez.',
      searchPlaceholder: 'Modelleri ara...',
      showAll: 'Tümünü Göster',
      hideAll: 'Tümünü Gizle',
      reset: 'Varsayılanlara Sıfırla',
      save: 'Değişiklikleri Kaydet',
      noModels: 'Model bulunamadı',
      modelsShown: '{{total}} modelden {{visible}} tanesi görünüyor',
      quotaManagement: 'Kota Yönetimi',
      hidden: 'Gizli',
      noModelsFound: 'Model bulunamadı',
      totalModels: 'Toplam',
      visibleModels: 'Görünen',
      hiddenModels: 'Gizli',
      saving: 'Kaydediliyor...',
    },
    providerGroupings: {
      title: 'Sağlayıcı Grupları',
      description: 'Daha iyi organizasyon için modelleri sağlayıcıya göre gruplayın',
      enabled: 'Sağlayıcı Gruplamasını Etkinleştir',
      models: '{{count}} model',
      avgLabel: 'ort',
      resetLabel: 'sıfırla',
      overall: 'Genel',
      healthy: 'Sağlıklı',
      degraded: 'Düşük Performans',
      limited: 'Sınırlı',
      critical: 'Kritik',
    },
    examples: {
      title: 'Kullanım Örnekleri',
      description: "Yerel API proxy'sini çağırmak için örnek komutlar.",
      curl: 'cURL',
      python: 'Python',
      copy: 'Kopyala',
      copied: 'Kopyalandı!',
      openai_protocol: 'OpenAI Protokolü',
      anthropic_protocol: 'Anthropic Protokolü',
      openai_tools: 'Cursor, Windsurf, NextChat',
      anthropic_tools: 'Claude Code CLI',
      flash: 'Hızlı',
      pro: 'Pro',
      flash_preview: 'Önizleme',
      pro_high: 'En İyi',
      sonnet: 'Düşünme (Thinking)',
      opus: 'Opus',
    },
    gateway: {
      title: 'API Proxy Hizmeti',
      description: 'Yerel API proxy sunucusunu kontrol edin.',
      status_running: 'Çalışıyor',
      status_stopped: 'Durduruldu',
      action_start: 'Hizmeti Başlat',
      action_stop: 'Hizmeti Durdur',
      accounts_info: '{{count}} hesap kullanılabilir',
      port: 'Dinleme Portu',
      port_hint: 'Varsayılan 8045, değişikliklerin uygulanması için yeniden başlatma gerekir',
      timeout: 'İstek Zaman Aşımı',
      timeout_hint: 'Varsayılan 120s, aralık 30-600s',
      api_key: 'API Anahtarı',
      regenerate_key: 'Yeniden Oluştur',
      regenerateConfirm: {
        title: 'API Anahtarı Yeniden Oluşturulsun mu?',
        description:
          'Bu işlem mevcut API anahtarını hemen geçersiz kılacaktır. Eski anahtarı kullanan tüm uygulamalar çalışmayı durduracaktır.',
        cancel: 'İptal',
        confirm: 'Yeniden Oluştur',
      },
      key_warning: 'API anahtarınızı güvende tutun. Kimseyle paylaşmayın.',
      auto_start: 'Uygulama ile Otomatik Başlat',
      auto_start_desc: 'Uygulama başlatıldığında proxy hizmetini de başlat',
    },
    proxy_tab: 'Proxy',
    save: 'Ayarları Kaydet',
  },
  toast: {
    backupSuccess: {
      title: 'Başarılı',
      description: 'Hesap yedeği başarıyla oluşturuldu.',
    },
    backupError: {
      title: 'Hata',
      description: 'Yedek oluşturulamadı: {{error}}',
    },
    switchSuccess: {
      title: 'Başarılı',
      description: 'Hesap başarıyla değiştirildi.',
    },
    switchError: {
      title: 'Hata',
      description: 'Hesap değiştirilemedi: {{error}}',
    },
    deleteSuccess: {
      title: 'Başarılı',
      description: 'Hesap yedeği başarıyla silindi.',
    },
    deleteError: {
      title: 'Hata',
      description: 'Yedek silinemedi: {{error}}',
    },
  },
  cloud: {
    title: 'Hesaplar',
    description: 'Google Gemini hesap havuzunuzu yönetin.',
    autoSwitch: 'Otomatik Değiştir',
    providerGroupings: 'Sağlayıcı Grupları',
    addAccount: 'Hesap Ekle',
    syncFromIDE: "IDE'den Eşitle",
    checkQuota: 'Kotayı Şimdi Kontrol Et',
    polling: 'Sorgulama tetiklendi',
    globalQuota: 'Genel Kota',
    layout: {
      auto: 'Otomatik',
      twoCol: '2 Sütun',
      threeCol: '3 Sütun',
      list: 'Liste',
      compact: 'Sıkışık',
    },
    authDialog: {
      title: 'Google Hesabı Ekle',
      description: 'Bir hesap eklemek için uygulamaya yetki vermeniz gerekir.',
      oauthClient: 'OAuth İstemcisi',
      oauthClientPlaceholder: 'OAuth istemcisini seçin',
      openLogin: 'Giriş Sayfasını Aç',
      authCode: 'Yetkilendirme Kodu',
      placeholder: '4/ ile başlayan kodu yapıştırın...',
      instruction:
        'Google girişi için varsayılan tarayıcı açılacaktır. Localhost sayfasındaki kodu kopyalayıp buraya yapıştırın.',
      verify: 'Doğrula ve Ekle',
    },
    card: {
      active: 'Aktif',
      use: 'Kullan',
      rateLimited: 'Hız Sınırına Takıldı',
      validationRiskControlled: 'Risk / Hız Sınırı',
      validationOAuthReauthRequired: 'OAuth Yeniden Yetkilendirme Gerekiyor',
      validationRequired: 'Doğrulama Gerekiyor',
      left: 'kaldı',
      used: 'Kullanılan',
      unknown: 'Bilinmeyen Kullanıcı',
      actions: 'İşlemler',
      useAccount: 'Hesabı Kullan',
      identityProfile: 'Kimlik Profili',
      refresh: 'Kotayı Yenile',
      delete: 'Hesabı Sil',
      noQuota: 'Kota verisi yok',
      rateLimitedQuota: 'Hız Sınırına Takıldı',
      resetPrefix: 'sıfırlama',
      resetTime: 'Sıfırlanma zamanı',
      resetUnknown: 'Bilinmeyen',
      gemini3Ready: 'Gemini 3 Hazır',
      groupGoogleGemini: 'Google Gemini',
      groupAnthropicClaude: 'Anthropic Claude',
      proxy: 'Proxy',
      proxyPlaceholder: 'örn. http://127.0.0.1:7890',
      proxySaved: 'Proxy kaydedildi',
      noProxy: 'Proxy yok',
      aiCredits: 'Yapay Zeka Kredileri',
      aiCreditsValue: '{{amount}} kredi',
      creditsExpiry: 'son kullanma tarihi {{date}}',
      modelVisibility: 'Model Görünürlüğü',
    },
    identity: {
      title: 'Kimlik Profili',
      loading: 'Yükleniyor...',
      generateAndBind: 'Oluştur ve Bağla',
      captureAndBind: 'Mevcut Olanı Yakala ve Bağla',
      restoreOriginal: 'Temel Profili Geri Yükle',
      openFolder: 'Kimlik Depolama Klasörünü Aç',
      previewTitle: 'Oluşturulan Kimlik Önizlemesi',
      confirm: 'Onayla',
      cancel: 'İptal',
      close: 'Kapat',
      currentStorage: 'Geçerli Çalışma Zamanı Kimliği',
      accountBinding: 'Bağlı Hesap Kimliği',
      history: 'Kimlik Geçmişi',
      noHistory: 'Kimlik geçmişi yok',
      current: 'Aktif',
      restore: 'Geri Yükle',
      generateSuccess: 'Kimlik oluşturuldu ve bağlandı',
      captureSuccess: 'Mevcut kimlik yakalandı ve bağlandı',
      restoreOriginalSuccess: 'Temel kimlik geri yüklendi',
      restoreVersionSuccess: 'Geçmiş kimlik geri yüklendi',
      deleteVersionSuccess: 'Geçmiş kimlik silindi',
      openFolderSuccess: 'Kimlik depolama klasörü açıldı',
      baseline: 'Temel Kimlik',
    },
    list: {
      noAccounts: 'Henüz bulut hesabı eklenmedi.',
    },
    error: {
      loadFailed: 'Bulut hesapları yüklenemedi.',
    },
    toast: {
      syncSuccess: {
        title: 'Eşitleme Başarılı',
        description: "IDE'den {{email}} içe aktarıldı.",
      },
      syncFailed: {
        title: 'Eşitleme Başarısız',
        description: 'IDE veritabanında aktif bir hesap bulunamadı.',
      },
      addSuccess: 'Hesap başarıyla eklendi!',
      addFailed: {
        title: 'Hesap eklenemedi',
      },
      quotaRefreshed: 'Kota yenilendi',
      refreshFailed: 'Kota yenilenemedi',
      pollFailed: 'Tüm hesaplar için kota sorgulanamadı',
      switched: {
        title: 'Hesap değiştirildi!',
        description: 'Antigravity yeniden başlatılıyor...',
      },
      switchFailed: 'Hesap değiştirilemedi',
      deleted: 'Hesap silindi',
      deleteFailed: 'Hesap silinemedi',
      deleteConfirm: 'Bu hesabı silmek istediğinizden emin misiniz?',
      autoSwitchOn: 'Otomatik Değiştirme Etkin',
      autoSwitchOff: 'Otomatik Değiştirme Devre Dışı',
      updateSettingsFailed: 'Ayarlar güncellenemedi',
      actionFailed: 'İşlem başarısız oldu',
      startAuthFailed: 'Oturum açma akışı başlatılamadı',
      refreshCreditsAvailable: 'Yapay Zeka kredileri: {{amount}}',
      refreshCreditsUnavailable: 'Bu yenileme için Yapay Zeka kredileri mevcut değil.',
      batchRefreshSuccess: '{{count}} hesap başarıyla yenilendi.',
      batchRefreshPartial: {
        title: 'Yenileme sorunlarla tamamlandı',
        description: '{{successful}} hesap yenilendi, {{failed}} başarısız oldu.',
      },
      batchDeleteSuccess: '{{count}} hesap başarıyla silindi.',
      batchDeletePartial: {
        title: 'Silme işlemi sorunlarla tamamlandı',
        description: '{{successful}} hesap silindi, {{failed}} başarısız oldu.',
      },
    },
    batch: {
      selected: '{{count}} adet seçildi',
      delete: 'Seçilenleri Sil',
      refresh: 'Seçilenleri Yenile',
      selectAll: 'Tümünü Seç',
      clear: 'Seçimi Temizle',
      confirmDelete: '{{count}} hesabı silmek istediğinizden emin misiniz?',
    },
    sort: {
      recentlyUsed: 'Son Kullanılanlar',
      quotaOverall: 'Genel Kota',
      quotaClaude: 'Claude Kotası',
      quotaPro3: 'Pro3 Kotası',
      quotaFlash: 'Flash Kotası',
    },
    exportImport: {
      export: 'Dışa Aktar',
      import: 'İçe Aktar',
      exportTitle: 'Hesapları Dışa Aktar',
      exportDesc:
        'Dışa aktarma dosyasına kimlik doğrulama belirteçlerinin (token) dahil edilip edilmeyeceğini seçin.',
      includeTokens: 'Belirteçleri dahil et (daha az güvenli)',
      stripTokens: 'Belirteçleri çıkar (paylaşım için daha güvenli)',
      exportSuccess: 'Hesaplar başarıyla dışa aktarıldı',
      importTitle: 'Hesapları İçe Aktar',
      importDesc: 'Daha önce dışa aktarılmış bir JSON dosyası seçin.',
      importStrategy: 'İçe Aktarma Stratejisi',
      strategyMerge: 'Birleştir - Mevcut olanları güncelle, yenileri ekle',
      strategyOverwrite: 'Üzerine Yaz - Tüm mevcut verileri değiştir',
      strategySkip: 'Atla - Sadece yeni hesapları ekle',
      importSuccess: '{{imported}} içe aktarıldı, {{updated}} güncellendi, {{skipped}} atlandı',
      importErrors: 'İçe aktarma işlemi {{count}} hata ile tamamlandı',
      selectFile: 'Dosya Seç',
      importing: 'İçe aktarılıyor...',
      fileTooLarge: 'Dosya boyutu 5MB sınırını aşıyor',
      invalidJson: 'Geçersiz JSON dosya biçimi',
      readFileFailed: 'Dosya okunamadı',
    },
  },
  proxy: {
    title: 'API Proxy',
    description: 'Yerel API proxy hizmetini yönetin.',
    save: 'Ayarları Kaydet',
    copy: 'Kopyala',
    copied: 'Kopyalandı!',
    regenerate: 'Yeniden Oluştur',
    regenerateConfirm: {
      title: 'API Anahtarı Yeniden Oluşturulsun mu?',
      description:
        'Bu işlem mevcut API anahtarını hemen geçersiz kılacaktır. Eski anahtarı kullanan tüm uygulamalar çalışmayı durduracaktır.',
      cancel: 'İptal',
      confirm: 'Yeniden Oluştur',
    },
    service: {
      title: 'Hizmet Durumu',
      description: 'Yerel API proxy sunucusunu kontrol edin.',
      running: 'Çalışıyor',
      stopped: 'Durduruldu',
      start: 'Hizmeti Başlat',
      stop: 'Hizmeti Durdur',
    },
    config: {
      port: 'Dinleme Portu',
      timeout: 'İstek Zaman Aşımı',
      api_key: 'API Anahtarı',
      auto_start: 'Uygulama ile Otomatik Başlat',
      auto_start_desc: 'Uygulama başlatıldığında proxy hizmetini de başlat',
      local_access: 'Yerel ağ erişimi:',
      select_ip: 'IP Seç',
      no_token_warning: '⚠️ API anahtarı ayarlanmadı. Erişim herkese açık!',
      show_key: 'Göster',
      hide_key: 'Gizle',
    },
    mapping: {
      title: 'Model Eşleme',
      description: 'Yönlendirme için Claude modellerini Gemini modelleriyle eşleyin.',
      maps_to: 'Şu modele eşlenir:',
      restore: 'Varsayılanlara Sıfırla',
    },
    examples: {
      title: 'Kullanım Örnekleri',
      description: "Yerel API proxy'sini çağırmak için örnek komutlar.",
    },
  },
};

export default tr;
