const zhCn = {
  appName: 'Antigravity 管理器',
  common: {
    loading: '加载中...',
    error: '错误',
    unknown: '未知',
    notAvailable: '不适用',
    openMenu: '打开菜单',
  },
  status: {
    checking: '正在检查状态...',
    running: 'Antigravity 正在后台运行',
    stopped: 'Antigravity 服务已停止',
  },
  action: {
    stop: '停止',
    start: '启动',
    switch: '切换',
    deleteBackup: '删除备份',
    backupCurrent: '备份当前账号',
    retry: '重试',
    details: '详情',
    openLogs: '打开日志目录',
  },
  update: {
    title: '更新',
    checking: '正在检查...',
    checkNow: '检查更新',
    checkFailed: '无法检查更新',
    upToDate: '当前已是最新版本。',
    unsupported: '当前平台不支持自动更新检查。',
    available: {
      title: '发现新版本',
      description: 'GitHub 上已有 {{version}} 版本。',
      download: '下载',
      dismiss: '关闭',
      macosUnsignedNote:
        'macOS 新版本未进行官方签名。如果系统阻止打开应用，请参考 GitHub README 或相关 issue 中的手动签名方式。',
    },
  },
  error: {
    generic: '发生未知错误。',
    detailsTitle: '错误详情',
    detailsDescription: '下面显示后端错误详情，可能包含本地文件路径和堆栈信息。',
    keychainUnavailable: 'Keychain 不可用。',
    keychainHint: {
      translocation: '检测到 macOS App Translocation。请将应用移动到 /Applications 后重试。',
      keychainDenied: 'Keychain 访问被拒绝。应用可能未签名，可参考 README 的“macOS 自签”说明。',
      signNotarize: '请在可用时使用已签名并公证的版本。',
    },
    dataMigrationFailed: '旧版账号数据无法解密。',
    dataMigrationHint: {
      relogin: '请重新登录或重新添加账号。',
      clearData: '如仍失败，请清理本地账号数据后再登录。',
    },
    antigravityStorageJsonNotFound:
      '未找到 Antigravity 的 storage.json。请先打开目标 Antigravity 应用并登录一次，生成身份存储后再重试切换。',
    antigravityProjectIdMissing:
      '该账号缺少 Antigravity 项目 ID。可能是该账号没有登录过 Antigravity 应用导致，请先在 Antigravity 应用中登录一次，再回到本工具重试切换。',
    antigravityDatabasePermissionDenied:
      'Antigravity 数据库存储目录不可写。请检查配置的 Antigravity user-data 目录，或先打开一次 Antigravity 后重启 Antigravity 管理器。',
    cloudAccountLoginExpired: '该邮箱的登录信息已过期，请重新登录。',
  },
  nav: {
    accounts: '账号',
    proxy: 'API 反代',
    settings: '设置',
  },
  editionSelection: {
    title: '选择您的 Antigravity 版本',
    description: '选择您正在使用的 Antigravity 版本。这将帮助管理器连接到正确的应用程序。',
    edition1x: {
      name: 'Antigravity 1.x',
      description: '原始 Antigravity 应用程序。如果您使用的是旧版本，请选择此项。',
    },
    edition20: {
      name: 'Antigravity IDE',
      description: '新版 Antigravity IDE (2.0)。如果您使用的是最新的 IDE 版本，请选择此项。',
    },
    confirm: '继续',
  },
  account: {
    current: '当前',
    lastUsed: '上次使用 {{time}}',
    switchToAntigravity: '切换到 Antigravity',
    switchToIde: '切换到 Antigravity IDE',
  },
  home: {
    title: '账号列表',
    description: '管理您的 Antigravity Google Gemini 账号。',
    noBackups: {
      title: '未找到备份',
      description: '备份您当前的 Antigravity 账号以开始使用。',
      action: '备份当前账号',
    },
  },
  settings: {
    title: '设置',
    description: '管理应用偏好设置。',
    general: '常规',
    connection: '连接',
    models: '模型',
    appearance: {
      title: '外观',
      description: '自定义 Antigravity 管理器在您设备上的显示方式。',
    },
    darkMode: '深色模式',
    darkModeDescription: '启用深色模式以获得更好的夜间观看体验。',
    language: {
      title: '语言',
      description: '选择您的首选语言。',
      english: '英语',
      chinese: '中文 (简体)',
      russian: '俄语',
      vietnamese: '越南语',
      turkish: '土耳其语',
      french: '法语',
    },
    about: {
      title: '关于',
      description: '应用信息。',
    },
    version: '版本',
    platform: '平台',
    license: '许可证',
    openLogDir: '打开',
    toast: {
      saved: {
        title: '设置已保存',
        description: '配置已更新。',
      },
      saveFailed: {
        title: '保存设置失败',
      },
    },
    account: {
      title: '账号设置',
      description: '配置自动刷新和同步账号。',
      auto_refresh: '自动刷新配额',
      auto_refresh_desc: '定期自动刷新所有账号的配额信息',
      auto_sync: '自动获取当前账号',
      auto_sync_desc: '定期自动同步当前活跃账号信息',
      antigravity_executable: 'Antigravity 可执行文件',
      antigravity_executable_desc: '可选路径，用于发现便携模式数据目录并启动 Antigravity。',
      antigravity_executable_placeholder: '例如：C:\\Program Files\\Antigravity\\Antigravity.exe',
      antigravity_ide_executable: 'Antigravity IDE 可执行文件',
      antigravity_ide_executable_desc:
        '可选的 Antigravity IDE 可执行文件路径。切换经典版账号时，会保护此路径下的进程不被终止。',
      antigravity_ide_executable_placeholder:
        '例如：C:\\Program Files\\Antigravity IDE\\Antigravity IDE.exe',
      antigravity_args: 'Antigravity 启动参数',
      antigravity_args_desc: '启动 Antigravity 时传入的可选参数，例如 --user-data-dir。',
      antigravity_args_placeholder: '例如：--user-data-dir D:\\AntigravityProfile',
      antigravity_ide_args: 'Antigravity IDE 启动参数',
      antigravity_ide_args_desc: '启动 Antigravity IDE 时传入的可选参数，例如 --user-data-dir。',
      antigravity_ide_args_placeholder: '例如：--user-data-dir D:\\AntigravityIdeProfile',
      detect_antigravity_args: '检测',
    },
    startup: {
      title: '启动',
      description: '控制系统启动时的应用行为。',
      auto_startup: '随系统启动',
      auto_startup_desc: '登录时自动启动并保持在托盘里',
      macos_hint: 'macOS 需要应用已签名才可生效。如自启动失败，请自行签名或在系统设置中手动启用。',
    },
    privacy: {
      title: '隐私',
      description: '控制你的数据如何用于改进应用。',
      error_reporting: '错误上报',
      error_reporting_desc: '发送匿名错误报告以帮助我们改进应用。不收集个人数据。',
      telemetry: '性能遥测',
      telemetry_desc: '分享匿名耗时指标和链路数据，用于诊断账号切换变慢问题。',
      clarity: 'Microsoft Clarity',
      clarity_desc: '分享匿名交互诊断、热图和会话回放，帮助改进应用体验。',
      clarity_unavailable: '当前构建未配置 Microsoft Clarity。',
      restart_note: '部分可观测性设置会在重启应用后生效。',
    },
    notifications: {
      title: '通知',
      description: '配置账号事件的桌面提醒。',
      quotaAlert: '低配额提醒',
      quotaAlertDesc: '当模型配额低于设定阈值时收到提醒',
      quotaThreshold: '提醒阈值',
      quotaThresholdDesc: '触发提醒的百分比阈值',
      saveFailed: '保存通知设置失败',
      thresholdSaveFailed: '保存阈值设置失败',
    },
    proxy: {
      title: '上游代理',
      description: '为发往 Google/Gemini API 的请求配置代理。',
      enable: '启用上游代理',
      url: '代理地址',
      timeout: '请求超时 (秒)',
    },
    modelMapping: {
      title: '模型映射',
      description: '将 Claude Code 模型映射到 Antigravity 模型，智能路由请求以优化成本和速度。',
      claudeKeyword: 'Claude 模型 (关键词)',
      targetGemini: '目标 Gemini 模型',
      addPlaceholderKey: '例如 op-3',
      addPlaceholderValue: '例如 gemini-3-flash',
      noMappings: '暂无自定义映射。',
      mapsTo: '映射到',
      default: '默认',
      restoreDefaults: '恢复默认配置',
    },
    modelVisibility: {
      title: '模型可见性',
      description: '控制哪些模型在账号卡片中可见。隐藏的模型不会在配额显示中出现。',
      searchPlaceholder: '搜索模型...',
      showAll: '显示全部',
      hideAll: '隐藏全部',
      reset: '重置为默认',
      save: '保存更改',
      noModels: '未找到模型',
      modelsShown: '{{visible}} / {{total}} 个模型可见',
      quotaManagement: '配额管理',
      hidden: '已隐藏',
      noModelsFound: '未找到模型',
      totalModels: '总数',
      visibleModels: '可见',
      hiddenModels: '隐藏',
      saving: '保存中...',
    },
    providerGroupings: {
      title: '模型分组',
      description: '按供应商分组模型以便更好地管理',
      enabled: '启用供应商分组',
      models: '{{count}} 个模型',
      avgLabel: '平均',
      resetLabel: '重置',
      overall: '总览',
      healthy: '正常',
      degraded: '降级',
      limited: '受限',
      critical: '严重',
    },

    examples: {
      title: '使用示例',
      description: '调用本地 API 代理的示例命令。',
      curl: 'cURL',
      python: 'Python',
      copy: '复制',
      copied: '已复制!',
      openai_protocol: 'OpenAI 协议',
      anthropic_protocol: 'Anthropic 协议',
      openai_tools: 'Cursor, Windsurf, NextChat',
      anthropic_tools: 'Claude Code CLI',
      flash: '极速',
      pro: '专业版',
      flash_preview: '预览版',
      pro_high: '最强',
      sonnet: '思维链',
      opus: 'Opus',
    },
    gateway: {
      title: 'API 反代服务',
      description: '控制本地 API 代理服务器。',
      status_running: '运行中',
      status_stopped: '已停止',
      action_start: '启动服务',
      action_stop: '停止服务',
      accounts_info: '{{count}} 个账号可用',
      port: '监听端口',
      port_hint: '默认 8045，修改端口需重启服务',
      timeout: '请求超时',
      timeout_hint: '默认 120 秒，范围 30-600 秒',
      api_key: 'API 密钥',
      regenerate_key: '重新生成',
      regenerateConfirm: {
        title: '重新生成 API 密钥？',
        description: '这将立即废除当前 API 密钥。任何使用旧密钥的应用将无法继续工作。',
        cancel: '取消',
        confirm: '重新生成',
      },
      key_warning: '请妥善保管您的 API 密钥，不要泄露给他人。',
      auto_start: '跟随应用自动启动',
      auto_start_desc: '应用启动时自动启动代理服务',
    },
    proxy_tab: '反代',
    save: '保存设置',
  },
  toast: {
    backupSuccess: {
      title: '成功',
      description: '账号备份创建成功。',
    },
    backupError: {
      title: '错误',
      description: '创建备份失败：{{error}}',
    },
    switchSuccess: {
      title: '成功',
      description: '切换账号成功。',
    },
    switchError: {
      title: '错误',
      description: '切换账号失败：{{error}}',
    },
    deleteSuccess: {
      title: '成功',
      description: '账号备份删除成功。',
    },
    deleteError: {
      title: '错误',
      description: '删除备份失败：{{error}}',
    },
  },
  cloud: {
    title: '账号列表',
    description: '管理您的 Google Gemini 账号池。',
    autoSwitch: '自动切换',
    providerGroupings: '提供商分组',
    addAccount: '添加账号',
    syncFromIde: '从 IDE 同步',
    checkQuota: '立即检查配额',
    polling: '已触发轮询',
    globalQuota: '全局配额',
    layout: {
      auto: '自动',
      twoCol: '2 列',
      threeCol: '3 列',
      list: '列表',
      compact: '紧凑',
    },
    authDialog: {
      title: '添加 Google 账号',
      description: '添加账号需要进行应用授权。',
      oauthClient: 'OAuth 客户端',
      oauthClientPlaceholder: '请选择 OAuth 客户端',
      openLogin: '打开登录页面',
      authCode: '授权码',
      placeholder: '粘贴以 4/ 开头的代码...',
      instruction: '将打开默认浏览器进行 Google 登录授权，自动获取并保存 Token。',
      verify: '验证并添加',
    },
    card: {
      active: '活跃',
      use: '使用',
      rateLimited: '受限',
      validationRiskControlled: '风控 / 限流',
      validationOAuthReauthRequired: '需要重新 OAuth 授权',
      validationRequired: '需要校验',
      left: '剩余',
      used: '已用',
      unknown: '未知用户',
      actions: '操作',
      useAccount: '使用账号',
      identityProfile: '身份配置',
      refresh: '刷新配额',
      delete: '删除账号',
      noQuota: '无配额数据',
      rateLimitedQuota: '已达限额',
      resetPrefix: '重置',
      resetTime: '重置时间',
      resetUnknown: '未知',
      gemini3Ready: 'Gemini 3 就绪',
      groupGoogleGemini: 'Google Gemini',
      groupAnthropicClaude: 'Anthropic Claude',
      proxy: '代理',
      proxyPlaceholder: '例如 http://127.0.0.1:7890',
      proxySaved: '代理已保存',
      noProxy: '无代理',
      aiCredits: 'AI 积分',
      aiCreditsValue: '{{amount}} 积分',
      creditsExpiry: '{{date}} 过期',
      modelVisibility: '模型可见性',
    },
    identity: {
      title: '身份配置',
      loading: '加载中...',
      generateAndBind: '生成并绑定',
      captureAndBind: '采集当前并绑定',
      restoreOriginal: '恢复基线配置',
      openFolder: '打开身份存储目录',
      previewTitle: '生成配置预览',
      confirm: '确认',
      cancel: '取消',
      close: '关闭',
      currentStorage: '当前运行配置',
      accountBinding: '账号绑定配置',
      history: '配置历史',
      noHistory: '暂无配置历史',
      current: '当前生效',
      restore: '恢复',
      generateSuccess: '生成并绑定成功',
      captureSuccess: '采集当前并绑定成功',
      restoreOriginalSuccess: '基线配置已恢复',
      restoreVersionSuccess: '历史配置已恢复',
      deleteVersionSuccess: '历史配置已删除',
      openFolderSuccess: '身份存储目录已打开',
      baseline: '基线配置',
    },
    list: {
      noAccounts: '暂无云账号。',
      noFilteredAccounts: '没有账号匹配所选套餐。',
    },
    error: {
      loadFailed: '加载云账号失败。',
      dataRepair: {
        title: '加密账号数据需要修复',
        description:
          '应用无法解密本地账号数据。通常是因为这些数据由另一把加密密钥创建，或本地数据已经损坏。',
        stepReLogin: '先重新登录或重新添加受影响的账号。',
        stepMacPrivacy:
          '在 macOS 上，检查钥匙串/隐私权限提示。如果应用未签名或重新签名过，请重新签名、移动到 /Applications 后再打开。',
        stepCheckGithub: '查看 GitHub 仓库首页 README 中最新的排查步骤。',
        stepOpenIssue: '清理本地账号数据前，先在 GitHub Issues 中搜索这个错误。',
        openRepository: '打开 GitHub 仓库',
        openIssues: '打开 GitHub Issues',
      },
    },
    toast: {
      syncSuccess: {
        title: '同步成功',
        description: '已从 IDE 导入 {{email}}。',
      },
      syncFailed: {
        title: '同步失败',
        description: 'IDE 数据库中未找到活跃账号。',
      },
      addSuccess: '账号添加成功！',
      addFailed: {
        title: '添加账号失败',
      },
      quotaRefreshed: '配额已刷新',
      refreshFailed: '刷新配额失败',
      pollFailed: '轮询所有账号配额失败',
      switched: {
        title: '账号已切换！',
        description: '正在重启 Antigravity...',
      },
      switchFailed: '切换账号失败',
      deleted: '账号已删除',
      deleteFailed: '删除账号失败',
      deleteConfirm: '确定要删除此账号吗？',
      autoSwitchOn: '自动切换已启用',
      autoSwitchOff: '自动切换已禁用',
      updateSettingsFailed: '更新设置失败',
      actionFailed: '操作失败',
      startAuthFailed: '启动登录流程失败',
      refreshCreditsAvailable: 'AI 积分：{{amount}}',
      refreshCreditsUnavailable: '本次刷新没有可用的 AI 积分信息。',
      batchRefreshSuccess: '成功刷新 {{count}} 个账号。',
      batchRefreshPartial: {
        title: '刷新已完成，但存在问题',
        description: '已刷新 {{successful}} 个账号，{{failed}} 个失败。',
      },
      batchDeleteSuccess: '成功删除 {{count}} 个账号。',
      batchDeletePartial: {
        title: '删除已完成，但存在问题',
        description: '已删除 {{successful}} 个账号，{{failed}} 个失败。',
      },
    },
    batch: {
      selected: '已选 {{count}} 项',
      delete: '删除选中',
      refresh: '刷新选中',
      selectAll: '全选',
      clear: '取消选择',
      confirmDelete: '确定要删除选中的 {{count}} 个账号吗？',
    },
    tierFilter: {
      all: '全部套餐',
      reset: '重置为全部',
      selectedCount: '{{count}} 个套餐',
      unknown: '未知',
    },
    sort: {
      recentlyUsed: '最近使用',
      quotaOverall: '总体配额',
      quotaClaude: 'Claude 配额',
      quotaPro3: 'Pro3 配额',
      quotaFlash: 'Flash 配额',
    },
    exportImport: {
      export: '导出',
      import: '导入',
      exportTitle: '导出账号',
      exportDesc: '选择是否在导出文件中包含认证令牌。',
      includeTokens: '包含令牌（安全性较低）',
      stripTokens: '移除令牌（适合分享）',
      exportSuccess: '账号导出成功',
      importTitle: '导入账号',
      importDesc: '选择之前导出的 JSON 文件。',
      importStrategy: '导入策略',
      strategyMerge: '合并 - 更新已有，添加新账号',
      strategyOverwrite: '覆盖 - 替换所有已有数据',
      strategySkip: '跳过 - 仅添加新账号',
      importSuccess: '导入 {{imported}}，更新 {{updated}}，跳过 {{skipped}}',
      importErrors: '导入完成，但有 {{count}} 个错误',
      selectFile: '选择文件',
      importing: '导入中...',
      fileTooLarge: '文件大小超过 5MB 限制',
      invalidJson: 'JSON 文件格式无效',
      readFileFailed: '读取文件失败',
    },
  },
  proxy: {
    title: 'API 反代',
    description: '管理本地 API 代理服务。',
    save: '保存设置',
    copy: '复制',
    copied: '已复制!',
    regenerate: '重新生成',
    regenerateConfirm: {
      title: '重新生成 API 密钥？',
      description: '这将立即废除当前 API 密钥。任何使用旧密钥的应用将无法继续工作。',
      cancel: '取消',
      confirm: '重新生成',
    },
    service: {
      title: '服务状态',
      description: '控制本地 API 代理服务器。',
      running: '运行中',
      stopped: '已停止',
      start: '启动服务',
      stop: '停止服务',
    },
    config: {
      port: '监听端口',
      timeout: '请求超时',
      api_key: 'API 密钥',
      auto_start: '随应用启动',
      auto_start_desc: '应用启动时自动启动代理服务',
      cloud_code_meta: 'Cloud Code 元数据块',
      cloud_code_meta_desc:
        '注入非标准 __cloudCodeMeta SSE 数据块，用于兼容旧版 Cloud Code。严格 OpenAI 客户端应保持关闭。',
      local_access: '局域网访问:',
      select_ip: '选择 IP',
      no_token_warning: '⚠️ 未设置 API 密钥。服务对公网开放！',
      show_key: '显示密钥',
      hide_key: '隐藏密钥',
    },
    mapping: {
      title: '模型映射',
      description: '将 Claude 模型映射到 Gemini 模型进行路由。',
      maps_to: '映射到',
      restore: '恢复默认',
    },
    examples: {
      title: '使用示例',
      description: '调用本地 API 代理的示例命令。',
    },
  },
};
export default zhCn;
